(async()=>{
  'use strict';

  const APP_KEY='life-unloaded-2026-v1';
  const VERSION='5.0.2',SCHEMA_VERSION=7,CONTENT_REVISION=6;
  const DEBUG=new URLSearchParams(location.search).get('debug')==='1';
  const app=document.getElementById('app');
  const copy=value=>JSON.parse(JSON.stringify(value));
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const money=value=>{const n=Number(value)||0,abs=Math.abs(n);if(abs>=1e12)return`${(n/1e12).toFixed(2)}万亿`;if(abs>=1e8)return`${(n/1e8).toFixed(2)}亿`;if(abs>=1e4)return`${(n/1e4).toFixed(abs>=1e6?0:1)}万`;return Math.round(n).toLocaleString('zh-CN')};
  const hashSeed=value=>{let h=2166136261;for(const char of String(value)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const makeSeed=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const getPath=(object,path)=>String(path).split('.').reduce((value,key)=>value?.[key],object);
  const setPath=(object,path,value)=>{const keys=String(path).split('.');let target=object;for(const key of keys.slice(0,-1)){if(!target[key]||typeof target[key]!=='object')target[key]={};target=target[key]}target[keys.at(-1)]=value;return value};
  const addPath=(object,path,value)=>setPath(object,path,(Number(getPath(object,path))||0)+Number(value||0));
  const stageForAge=age=>Object.entries(DATA.stages).find(([,range])=>age>=range[0]&&age<=range[1])?.[0]||'elder';
  const weighted=(items,weightFn=item=>item.weight||1)=>{if(!items.length)return null;let total=items.reduce((sum,item)=>sum+Math.max(0,weightFn(item)),0),roll=rng()*total;for(const item of items){roll-=Math.max(0,weightFn(item));if(roll<=0)return item}return items.at(-1)};
  const chance=value=>rng()<value;
  let DATA,INDEX,state,inputLocked=false;
  function rng(){let x=state.run?.rngState||hashSeed(makeSeed());x^=x<<13;x^=x>>>17;x^=x<<5;if(state.run)state.run.rngState=x>>>0;return(x>>>0)/4294967296}
  function stable(seed,key,max=100){return hashSeed(`${seed}:${key}`)%max}

  function defaultMeta(){return{schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,histories:[],legacyHistories:[],codex:[],settings:{haptic:true,reducedMotion:false},stats:{runs:0},seen:{events:{},cards:{},families:{},endings:{}},recentSeeds:[],migrationNotice:false}}
  function normalizeMeta(meta={}){const fresh=defaultMeta();return{...fresh,...meta,schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,settings:{...fresh.settings,...(meta.settings||{})},stats:{...fresh.stats,...(meta.stats||{})},seen:{...fresh.seen,...(meta.seen||meta.seenContent||{})},histories:Array.isArray(meta.histories)?meta.histories.slice(0,40):[],legacyHistories:Array.isArray(meta.legacyHistories)?meta.legacyHistories.slice(0,40):[],codex:Array.isArray(meta.codex)?meta.codex.filter(id=>INDEX.codex.has(id)):[],recentSeeds:Array.isArray(meta.recentSeeds)?meta.recentSeeds.slice(0,8):[]}}
  function buildIndex(){const kinds={},event=new Map(),cards=new Map(DATA.cards.map(card=>[card.id,card])),codex=new Map(DATA.codex.map(item=>[item.id,item]));for(const item of DATA.events){event.set(item.id,item);(kinds[item.kind]||(kinds[item.kind]=[])).push(item)}return{event,kinds,cards,codex}}

  function worldAt(age,location){const year=2026+age,decades=Math.floor(age/10),mods=location.mods;return{year,era:age<20?'转型初期':age<50?'高流动时代':age<80?'老龄社会':'远期社会',priceIndex:Number((1.025**age).toFixed(4)),laborMarket:clamp(62-decades*2+stable(location.id,`labor-${decades}`,20)-10,25,85),housingCost:mods.cost,medicalAccess:mods.medical,retirementBase:age<40?63:65,digitalization:clamp(65+decades*4,0,100)}}
  function rangePick([min,max],key,seed){return min+stable(seed,key,max-min+1)}
  function person(id,relation,bornAt,extra={}){return{id,relation,bornAt,alive:true,health:65,bond:55,...extra}}
  function chooseFamily(run,location){const recent=new Set(state.meta.histories.slice(0,4).map(item=>item.familyId));return weighted(DATA.familyArchetypes,family=>(family.weight||10)*(family.locationAffinity.includes(location.id)?1.8:1)*(recent.has(family.id)?.35:1))}
  function createOrigin(run,location,family){
    const people=[],parentCount=family.parentCount,siblingCount=rangePick(family.siblingRange,'siblings',run.seed),jobs=family.parentJobs;
    if(parentCount>=1)people.push(person('father','father',-24-stable(run.seed,'father-age',18),{gender:'male',occupation:jobs[stable(run.seed,'father-job',jobs.length)],bond:clamp(38+family.expression/2,30,82)}));
    if(parentCount>=2)people.push(person('mother','mother',-22-stable(run.seed,'mother-age',16),{gender:'female',occupation:jobs[stable(run.seed,'mother-job',jobs.length)],bond:clamp(42+family.expression/2,32,86)}));
    for(let i=0;i<siblingCount;i++){const bornAt=stable(run.seed,`sibling-older-${i}`,2)?-(2+stable(run.seed,`sibling-age-${i}`,8)):2+stable(run.seed,`sibling-age-${i}`,7);people.push(person(`sibling_${i+1}`,'sibling',bornAt,{gender:stable(run.seed,`sibling-gender-${i}`,2)?'female':'male',bond:50,alive:bornAt<=0,status:bornAt<=0?'living':'unborn'}))}
    return{familyId:family.id,familyName:family.name,familyClass:family.familyClass,people,housing:family.housingOptions[stable(run.seed,'family-house',family.housingOptions.length)],assets:rangePick(family.assetRange,'family-assets',run.seed),debt:rangePick(family.debtRange,'family-debt',run.seed),cashflow:family.cashflow,control:family.control,expression:family.expression,careBurden:family.careBurden,riskTolerance:family.riskTolerance,digitalLiteracy:family.digitalLiteracy,secret:DATA.familySecrets.filter(secret=>secret.familyClasses.includes(family.familyClass))[stable(run.seed,'secret',DATA.familySecrets.filter(secret=>secret.familyClasses.includes(family.familyClass)).length)]||DATA.familySecrets[0]}
  }
  function initDesires(run){run.desires={};for(const[key,spec]of Object.entries(DATA.desires)){const familyBias=key==='freedom'?(run.originHousehold.control-50)*.25:key==='familyBelonging'?(run.originHousehold.expression-50)*.2:0;run.desires[key]={name:spec.name,drive:clamp(42+stable(run.seed,`desire-${key}`,30)+familyBias,15,90),fulfillment:50,claimed:false}}run.desires.reclaimed=false}
  function chooseConflict(run){return[...DATA.conflicts].sort((a,b)=>b.desires.reduce((sum,key)=>sum+run.desires[key].drive,0)-a.desires.reduce((sum,key)=>sum+run.desires[key].drive,0)+stable(run.seed,b.id,9)-stable(run.seed,a.id,9))[0].id}

  function createRun(seed=makeSeed()){
    const run={seed,rngState:hashSeed(seed),schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,contentRevision:CONTENT_REVISION,phase:'birth',age:0,gender:stable(seed,'gender',2)?'female':'male'};
    state.run=run;const location=weighted(DATA.locations),family=chooseFamily(run,location);run.location=location;run.originHousehold=createOrigin(run,location,family);run.people=[...run.originHousehold.people];
    run.attrs={intellect:1,physique:1,looks:1,stability:1,social:1,ambition:1};run.points=20;
    run.world=worldAt(0,location);run.education={status:'notStarted',level:0,path:null,field:null,credentials:[],years:0};run.roles=['child'];
    run.employment={status:'none',career:'尚未进入社会',sector:'none',employerType:'none',rank:0,contract:'none',salary:0,benefits:0,tenure:0,experience:0,publicExperience:0,arrangement:'onsite',schedule:{stability:70,splitGapHours:0,timezoneLoad:0}};
    run.activity={mode:'childhood',funding:'family',years:0};run.finance={cash:stable(seed,'child-cash',1500),available:0,assets:[],liabilities:[],equity:0,totalDebt:0,netWorth:0,lastIncome:0,lastExpense:0};run.housing={status:'family',value:0};
    run.relationships={originBond:55,partnerStatus:'none',partnerBond:0,parenthoodIntent:'undecided',childCount:0,childBond:0,network:clamp(35+location.mods.network/3,30,75)};
    run.health={physical:clamp(62+stable(seed,'health',30),50,92),mental:72,chronic:[],disability:'none',careNeed:0};run.habits={stage:'none',risk:0,type:null,recoveryYears:0};
    run.capabilities={skill:0,portableSkill:family.digitalLiteracy>=60?1:0,employability:50,publicCredential:0,evidence:0,network:0,resilience:0,cashBuffer:0,healthLiteracy:0,boundary:0,learning:0,riskSense:0,creativity:0,careSkill:0,negotiation:0};
    run.mobility={mode:'home',platformDependence:0,rootlessness:0,visaPressure:0};run.business={mode:'none',status:'none',operatingSkill:clamp(25+family.riskTolerance/3,20,60),equity:0,scale:'none',control:100};
    run.pressures={money:0,family:0,career:0,body:0,loneliness:0};run.legacy={plan:'none',medicalDirective:'none'};run.obligations=[];run.arcs={};run.arcSlots={career:null,family:null,personal:null};
    initDesires(run);run.mainConflict=chooseConflict(run);run.outcomeTags={};run.decisionHistory=[];run.scheduledConsequences=[];run.usedConsequences=[];run.usedEvents=[];run.cards=[];run.cardAges=[];run.timeline=[];run.yearQueue=[];run.yearStarted=false;run.decisionCount=0;run.targetDecisions=16+stable(seed,'decision-target',5);run.lastDecisionAge=-5;run.stageDecisionCounts={};run.secretRevealed=false;run.lastSwanAge=-20;run.swanCount=0;run.agency=0;run.deathCause=null;run.naturalDeathAge=58+stable(seed,'lifespan',48);run.ending=null;syncDerived(run);return run;
  }

  function totalDebt(run){return run.finance.liabilities.filter(item=>item.status!=='settled').reduce((sum,item)=>sum+Math.max(0,item.principal),0)}
  function personalAssets(run){return run.finance.assets.reduce((sum,item)=>sum+(item.value||0),0)+(run.housing.status==='owned'||run.housing.status==='mortgaged'?run.housing.value:0)+run.business.equity}
  function childPeople(run){return run.people.filter(item=>item.alive&&['child','adoptedChild','stepChild'].includes(item.relation))}
  function partnerPeople(run){return run.people.filter(item=>item.alive&&item.relation==='partner')}
  function syncDerived(run){run.age=clamp(run.age,0,105);run.world=worldAt(run.age,run.location);run.relationships.childCount=childPeople(run).length;run.finance.totalDebt=totalDebt(run);run.finance.available=run.finance.cash;run.finance.netWorth=run.finance.cash+personalAssets(run)-run.finance.totalDebt;run.relationships.partnerBond=partnerPeople(run)[0]?.bond??(run.relationships.partnerStatus==='none'?0:run.relationships.partnerBond);if(run.employment.status==='employed'&&!run.roles.includes('employee'))run.roles.push('employee');if(run.relationships.childCount&&!run.roles.includes('parent'))run.roles.push('parent');if(['retired'].includes(run.activity.mode)&&!run.roles.includes('retiree'))run.roles.push('retiree');return run}

  function normalizeRun(run){const fresh=createRun(run.seed||makeSeed()),merged={...fresh,...run};for(const key of['education','employment','activity','finance','relationships','health','habits','capabilities','mobility','business','pressures','legacy','world'])merged[key]={...fresh[key],...(run[key]||{})};merged.employment.schedule={...fresh.employment.schedule,...(run.employment?.schedule||{})};for(const key of Object.keys(fresh.desires))if(key!=='reclaimed')merged.desires[key]={...fresh.desires[key],...(run.desires?.[key]||{})};merged.schemaVersion=SCHEMA_VERSION;merged.gameVersion=VERSION;merged.contentRevision=CONTENT_REVISION;return syncDerived(merged)}
  function validateRun(run){return Boolean(run&&run.location&&run.originHousehold&&run.education&&run.employment&&run.finance&&Array.isArray(run.people)&&run.relationships&&run.health&&run.habits&&run.arcs&&Array.isArray(run.decisionHistory)&&Number.isFinite(run.age)&&Number.isFinite(run.finance.cash))}
  function gameStorageKeys(){return Array.from({length:localStorage.length},(_,index)=>localStorage.key(index)).filter(key=>key?.startsWith('life-unloaded-2026-'))}
  function removeLegacySnapshots(){for(const key of gameStorageKeys())if(key!==APP_KEY)localStorage.removeItem(key)}
  function loadState(){
    const base={schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,meta:defaultMeta(),run:null,view:'home',drawer:false,recovery:null};const raw=localStorage.getItem(APP_KEY);if(!raw){removeLegacySnapshots();return base}
    try{const parsed=JSON.parse(raw),oldSchema=Number(parsed.schemaVersion||parsed.run?.schemaVersion||0),sameRelease=oldSchema===SCHEMA_VERSION&&parsed.gameVersion===VERSION;state=base;base.meta=normalizeMeta(parsed.meta||{});if(sameRelease)base.run=parsed.run?normalizeRun(parsed.run):null;else{base.run=null;base.meta.migrationNotice=true}removeLegacySnapshots();if(base.run&&base.run.phase!=='ended')base.view='game';persist(base,true);return base}catch(error){localStorage.removeItem(APP_KEY);removeLegacySnapshots();return{...base,recovery:{message:'存档无法读取，已清除损坏数据并重新开始。'}}}
  }
  function persist(value=state,force=false){if(!value||(!force&&value.run?.simulation))return;try{localStorage.setItem(APP_KEY,JSON.stringify({schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,meta:value.meta,run:value.run}))}catch(error){showToast('存档空间不足，请先导出档案')}}
  const save=force=>persist(state,force);

  function compare(actual,op,expected){if(op==='eq')return actual===expected;if(op==='neq')return actual!==expected;if(op==='gte')return Number(actual)>=Number(expected);if(op==='lte')return Number(actual)<=Number(expected);if(op==='gt')return Number(actual)>Number(expected);if(op==='lt')return Number(actual)<Number(expected);if(op==='in')return expected.includes(actual);if(op==='notIn')return!expected.includes(actual);if(op==='includes')return Array.isArray(actual)&&actual.includes(expected);if(op==='truthy')return Boolean(actual);return false}
  function predicateMatches(rule,run=state.run){const actual=rule.path==='age'?run.age:getPath(run,rule.path);return compare(actual,rule.op,rule.value)}
  function requirementsMatch(requirements={},run=state.run){const all=requirements.all||[],any=requirements.any||[],none=requirements.none||[];return all.every(rule=>predicateMatches(rule,run))&&(!any.length||any.some(rule=>predicateMatches(rule,run)))&&!none.some(rule=>predicateMatches(rule,run))}
  function personAge(item,run=state.run){return run.age-item.bornAt}
  function actorMatches(item,spec,run){if(spec.relation&&item.relation!==spec.relation)return false;if(spec.relationAny&&!spec.relationAny.includes(item.relation))return false;if(spec.alive!==undefined&&item.alive!==spec.alive)return false;if(spec.ageMin!==undefined&&personAge(item,run)<spec.ageMin)return false;if(spec.ageMax!==undefined&&personAge(item,run)>spec.ageMax)return false;if(spec.statusAny&&item.relation==='partner'&&!spec.statusAny.includes(run.relationships.partnerStatus))return false;return true}
  function resolveActors(event,run=state.run){const resolved={};for(const spec of event.actors||[]){const found=run.people.find(item=>actorMatches(item,spec,run));if(!found&&!spec.optional)return null;if(found)resolved[spec.slot]=found}return resolved}
  function arcEligible(event,run){if(!event.arc)return true;const record=run.arcs[event.arc.id],slot=run.arcSlots[event.arc.lane];if(event.arc.role==='start')return(!record||record.status==='inactive')&&(!slot||slot===event.arc.id);return Boolean(record&&record.status==='active'&&record.nextNode===event.arc.node&&run.age>=record.dueAge)}
  function eligible(event,run=state.run){if(!event||run.usedEvents.includes(event.id)||run.age<event.ageMin||run.age>event.ageMax)return false;if(!(event.stage||[]).includes(stageForAge(run.age)))return false;if(!requirementsMatch(event.requirements,run)||!arcEligible(event,run))return false;return Boolean(resolveActors(event,run))}

  function addTag(run,tag){run.outcomeTags[tag]=(run.outcomeTags[tag]||0)+1}
  function addLiability(run,command){run.finance.liabilities.push({id:`debt_${run.age}_${run.finance.liabilities.length+1}`,kind:command.kind||'consumer',principal:Math.max(0,Number(command.value)||0),rate:Number(command.rate)||.06,status:'current',guaranteed:Boolean(command.guaranteed),startedAt:run.age,arrears:0})}
  function transitionEducation(run,command){const levels={none:0,primary:1,middleSchool:2,highSchool:3,vocational:3,college:4,postgraduate:5};run.education.path=command.value;run.education.level=levels[command.value]??run.education.level;run.education.status=command.status||'enrolled';run.activity.mode=run.education.status==='enrolled'?'study':run.activity.mode;if(run.education.status==='enrolled'&&!run.roles.includes('student'))run.roles.push('student')}
  function createRelatedPerson(run,command){const relation=command.relation||'child',index=run.people.filter(item=>item.relation===relation).length+1;run.people.push(person(`${relation}_${index}`,relation,run.age,{bond:60,legalStatus:relation==='adoptedChild'?'adopted':'biological'}));if(['child','adoptedChild','stepChild'].includes(relation))run.relationships.parenthoodIntent='parent'}
  function applyCommands(commands=[],context={}){
    const run=state.run,before=copy(run);
    for(const command of commands){
      if(command.type==='add'){addPath(run,command.target,command.value);if(command.target==='relationships.partnerBond')for(const item of partnerPeople(run))item.bond=clamp(item.bond+Number(command.value),0,100);if(command.target==='relationships.childBond')for(const item of childPeople(run))item.bond=clamp(item.bond+Number(command.value),0,100)}
      else if(command.type==='set')setPath(run,command.target,command.value);
      else if(command.type==='tag')addTag(run,command.value);
      else if(command.type==='addLiability')addLiability(run,command);
      else if(command.type==='createPerson')createRelatedPerson(run,command);
      else if(command.type==='transition'&&command.target==='education')transitionEducation(run,command);
      else if(command.type==='claimDesire'){for(const[key,desire]of Object.entries(run.desires)){if(key==='reclaimed')continue;if(command.replace)desire.claimed=false}for(const key of command.value||[])if(run.desires[key]){run.desires[key].claimed=true;run.desires[key].drive=clamp(run.desires[key].drive+12,15,100)}if(command.replace)run.desires.reclaimed=true}
    }
    run.health.physical=clamp(run.health.physical,0,100);run.health.mental=clamp(run.health.mental,0,100);run.habits.risk=clamp(run.habits.risk,0,100);for(const key of Object.keys(run.pressures))run.pressures[key]=clamp(run.pressures[key],0,100);run.relationships.partnerBond=clamp(run.relationships.partnerBond,0,100);run.relationships.childBond=clamp(run.relationships.childBond,0,100);run.relationships.network=clamp(run.relationships.network,0,100);run.finance.cash=Math.max(-1e13,run.finance.cash);run.business.equity=Math.max(0,run.business.equity);syncDerived(run);return{before,after:copy(run),context}
  }

  function scheduleConsequence(event,choice){for(const spec of choice.consequences||[]){const consequence=INDEX.event.get(spec.eventId);if(!consequence?.choiceOutcomes?.[choice.memoryKey])continue;const dueAge=state.run.age+spec.delayMin+Math.floor(rng()*(spec.delayMax-spec.delayMin+1));state.run.scheduledConsequences.push({id:`${spec.eventId}:${choice.memoryKey}:${state.run.age}`,eventId:spec.eventId,memoryKey:choice.memoryKey,sourceDecisionId:event.id,sourceChoiceId:choice.id,dueAge,expiresAge:Math.min(105,dueAge+6),status:'scheduled'})}}
  function updateArc(event,choice){if(!event.arc)return;const run=state.run,arc=event.arc;let record=run.arcs[arc.id]||{id:arc.id,status:'inactive',route:null,nextNode:1,dueAge:run.age,startedAt:null,completedAt:null};if(arc.role==='start'){record.status='active';record.startedAt=run.age;run.arcSlots[arc.lane]=arc.id}record.route=choice.route||record.route;if(choice.arcExit){record.status='abandoned';record.completedAt=run.age;record.nextNode=arc.node;run.arcSlots[arc.lane]=null}else if(arc.role==='resolve'){record.status='resolved';record.completedAt=run.age;record.nextNode=arc.node;run.arcSlots[arc.lane]=null}else{record.status='active';record.nextNode=arc.node+1;record.dueAge=run.age+1+stable(run.seed,`${event.id}:${choice.id}:arc`,4)}run.arcs[arc.id]=record}
  function invalidateArc(event){if(!event.arc)return;const record=state.run.arcs[event.arc.id];if(record?.status==='active'){record.status='abandoned';record.completedAt=state.run.age;state.run.arcSlots[event.arc.lane]=null;addTimeline({id:`arc_abandoned_${event.arc.id}`,kind:'consequence',icon:'↩',track:event.track},`${TRACK_LABELS[event.track]||'这条路线'}因当前状态改变而明确结束。`)}}
  function impactScore(before,after,choice){let score=2;score+=Math.min(8,Math.abs(after.finance.netWorth-before.finance.netWorth)/20000);score+=Math.abs(after.health.physical-before.health.physical)/3+Math.abs(after.health.mental-before.health.mental)/3;score+=(choice.commitments?.length||0)*2;score+=(choice.outcomeTags?.length||0);return Math.round(score)}
  function chooseDecision(index){
    const run=state.run,event=run.currentDecision,choice=event?.choices?.[index];if(!choice||inputLocked||!requirementsMatch({all:choice.requirements||[]},run))return;inputLocked=true;
    const snapshot=copy(run),result=applyCommands(choice.effects,event);for(const tag of choice.outcomeTags||[])addTag(run,tag);scheduleConsequence(event,choice);updateArc(event,choice);
    run.decisionHistory.push({age:run.age,eventId:event.id,choiceId:choice.id,choice:choice.text,result:choice.resultText,stateBefore:{activity:snapshot.activity.mode,employment:snapshot.employment.status,partner:snapshot.relationships.partnerStatus,children:snapshot.relationships.childCount,netWorth:snapshot.finance.netWorth,health:snapshot.health.physical,habit:snapshot.habits.stage},stateAfter:{activity:run.activity.mode,employment:run.employment.status,partner:run.relationships.partnerStatus,children:run.relationships.childCount,netWorth:run.finance.netWorth,health:run.health.physical,habit:run.habits.stage},outcomeTags:[...(choice.outcomeTags||[])],commitments:choice.commitments||[],impact:impactScore(result.before,result.after,choice)});
    run.usedEvents.push(event.id);run.decisionCount++;run.lastDecisionAge=run.age;run.stageDecisionCounts[stageForAge(run.age)]=(run.stageDecisionCounts[stageForAge(run.age)]||0)+1;addTimeline(event,`${choice.text}。${choice.resultText}`,'chosen');run.currentDecision=null;run.phase='playing';run.yearStarted=false;settleYear(run);run.age++;syncDerived(run);save();render();setTimeout(()=>inputLocked=false,180)
  }

  const TRACK_LABELS={education:'教育',employment:'工作',public:'公共职业',remote:'远程生活',business:'经营',leisure:'不工作',partnership:'关系',children:'子女',finance:'财务',health:'健康',habits:'习惯',later:'晚年',origin:'出身',identity:'欲望'};
  function baseSalary(run){if(run.employment.status!=='employed')return 0;const education=[.65,.75,.85,1,1.25,1.55][run.education.level]||.65,rank=1+run.employment.rank*.18,sector=run.employment.employerType==='public'?.92:run.employment.sector==='digital'?1.35:1,market=.75+run.world.laborMarket/200;return Math.round(Math.max(18000,36000*education*rank*sector*market+run.employment.salary))}
  function livingCost(run){const base=16000*(run.location.mods.cost/100)*run.world.priceIndex,children=childPeople(run).filter(child=>personAge(child,run)<18).length*9000*run.world.priceIndex,housing=run.housing.status==='renting'?12000*(run.location.mods.cost/100)*run.world.priceIndex:0,care=run.activity.mode==='care'?8000*run.world.priceIndex:0;return Math.round(base+children+housing+care)}
  function settleLiabilities(run){for(const debt of run.finance.liabilities){if(debt.status==='settled')continue;debt.principal=Math.round(debt.principal*(1+debt.rate));const minimum=Math.round(debt.principal*(debt.kind==='mortgage'?.04:.10));if(run.finance.cash>=minimum){run.finance.cash-=minimum;debt.principal=Math.max(0,debt.principal-minimum);debt.arrears=Math.max(0,(debt.arrears||0)-1);if(debt.principal===0)debt.status='settled'}else{debt.arrears=(debt.arrears||0)+1;debt.status=debt.arrears>=2?'delinquent':'current';run.pressures.money=clamp(run.pressures.money+(debt.arrears>=2?8:4),0,100)}}}
  function settleBusiness(run){if(run.business.status!=='operating')return 0;const skill=run.business.operatingSkill,locationCost=run.location.mods.cost,lock=run.business.mode==='franchise'?18:0,readiness=skill*.6+(100-locationCost)*.25+stable(run.seed,`business-${run.age}`,100)*.15;let flow=Math.round((readiness-48)*3500*run.world.priceIndex-lock*1200);if(run.business.mode==='franchise')flow-=Math.round(16000*run.world.priceIndex);if(flow<0){run.pressures.money=clamp(run.pressures.money+6,0,100);run.pressures.family=clamp(run.pressures.family+3,0,100)}else{run.business.operatingSkill=clamp(run.business.operatingSkill+2,0,100);run.business.equity=Math.max(run.business.equity,Math.round(flow*4+run.business.equity*1.08));if(run.business.equity>=1e6)run.business.scale='regional';if(run.business.equity>=1e8)run.business.scale='national';if(run.business.equity>=1e12){run.business.scale='global';addTag(run,'wealthApex')}}return flow}
  function settleYear(run){
    if(run.age===0&&run.timeline.length<2)return;run.world=worldAt(run.age,run.location);let income=baseSalary(run),expense=livingCost(run);
    if(run.employment.status==='gig')income=Math.round((12000+stable(run.seed,`gig-${run.age}`,52000))*run.world.priceIndex*(1-run.mobility.platformDependence/180));
    if(run.activity.mode==='leisure'||run.activity.mode==='sabbatical'){income=run.activity.funding==='family'?Math.round(run.originHousehold.cashflow*250*run.world.priceIndex):0;if(run.activity.mode==='leisure')run.capabilities.employability=clamp(run.capabilities.employability-2,0,100)}
    if(run.activity.mode==='retired')income=Math.round((run.employment.publicExperience*350+12000)*run.world.priceIndex);
    income+=settleBusiness(run);if(run.employment.arrangement==='remote'||run.employment.arrangement==='hybrid')expense-=Math.round(4000*run.world.priceIndex);if(run.mobility.mode==='overseasNomad')expense+=Math.round(18000*run.world.priceIndex);
    if(run.employment.arrangement==='splitShift'){run.pressures.body=clamp(run.pressures.body+5,0,100);run.pressures.family=clamp(run.pressures.family+Math.round(run.employment.schedule.splitGapHours/2),0,100)}
    if(run.mobility.rootlessness>50)run.pressures.loneliness=clamp(run.pressures.loneliness+4,0,100);if(run.mobility.platformDependence>60)income=Math.round(income*(.72+stable(run.seed,`platform-${run.age}`,55)/100));
    run.finance.lastIncome=income;run.finance.lastExpense=expense;run.finance.cash+=income-expense;settleLiabilities(run);if(run.finance.cash<0){addLiability(run,{value:Math.abs(run.finance.cash),kind:'living',rate:.08});run.finance.cash=0;run.pressures.money=clamp(run.pressures.money+7,0,100)}
    if(run.pressures.body>=70)run.health.physical-=3;else if(run.pressures.body>=40)run.health.physical-=1;if(run.habits.stage==='dependent'){run.health.physical-=3;run.health.mental-=4;run.finance.cash-=Math.round(12000*run.world.priceIndex)}if(run.habits.stage==='recovery'){run.habits.recoveryYears++;run.habits.risk=clamp(run.habits.risk-4,0,100);run.health.mental=clamp(run.health.mental+2,0,100);if(run.habits.recoveryYears>=3)addTag(run,'recovery')}
    for(const key of Object.keys(run.pressures))if(run.pressures[key]>0)run.pressures[key]=clamp(run.pressures[key]-1,0,100);run.employment.tenure=run.employment.status==='employed'?run.employment.tenure+1:0;run.activity.years++;syncDerived(run);unlockCodex()
  }

  function educationMilestones(run){if(run.age===6&&run.education.status==='notStarted')transitionEducation(run,{value:'primary',status:'enrolled'});if(run.age===12&&run.education.path==='primary')transitionEducation(run,{value:'middleSchool',status:'enrolled'});if(run.age===15&&run.education.path==='middleSchool')run.education.status='completed';if(run.age===18&&['highSchool','vocational'].includes(run.education.path)&&run.education.status==='enrolled')run.education.status='completed';if(run.age===22&&run.education.path==='college'&&run.education.status==='enrolled'){run.education.status='completed';run.activity.mode='seeking';run.roles=run.roles.filter(role=>role!=='student')}}
  function updatePeople(run){for(const item of run.people){if(item.status==='unborn'&&run.age>=item.bornAt){item.status='living';item.alive=true;addTimeline({id:`person_birth_${item.id}_${run.age}`,icon:'·',kind:'consequence',track:'origin'},'家里迎来了一名新的兄弟姐妹。')}if(!item.alive)continue;const age=personAge(item,run);if(age>78&&stable(run.seed,`${item.id}:death:${run.age}`,100)<Math.min(45,(age-74)*3)){item.alive=false;item.status='deceased';if(item.relation==='partner'){run.relationships.partnerStatus='widowed';addTag(run,'widowed')}addTimeline({id:`person_loss_${item.id}_${run.age}`,icon:'·',kind:'consequence',track:'later'},`${item.relation==='father'?'父亲':item.relation==='mother'?'母亲':item.relation==='partner'?'伴侣':'一位家人'}在这一年离世。`)}}}
  function mortality(run){if(run.deathCause)return true;const ageRisk=run.age<1?.002:run.age<12?.0003:run.age<40?.0006:run.age<60?.002:run.age<75?.012:.035+(run.age-75)*.005,healthRisk=run.health.physical<20?.18:run.health.physical<40?.04:0,habitRisk=run.habits.stage==='dependent'?.018:0;if(run.age>=run.naturalDeathAge||chance(Math.min(.85,ageRisk+healthRisk+habitRisk))){run.deathCause=run.age<18?'疾病或事故':run.health.physical<30?'长期健康问题':run.habits.stage==='dependent'?'失控留下的身体后果':'自然衰老';if(run.age<45)addTag(run,'earlyDeath');return true}return false}

  function dueConsequence(run){const schedule=run.scheduledConsequences.filter(item=>item.status==='scheduled'&&item.dueAge<=run.age&&item.expiresAge>=run.age).sort((a,b)=>a.dueAge-b.dueAge)[0];if(!schedule)return null;const event=INDEX.event.get(schedule.eventId),outcome=event?.choiceOutcomes?.[schedule.memoryKey];if(!event||!outcome){schedule.status='invalidated';return null}return{...event,runtimeText:outcome.text,runtimeEffects:outcome.effects,runtimeTags:outcome.outcomeTags,scheduleId:schedule.id}}
  function dueSecret(run){const secret=run.originHousehold.secret;if(run.secretRevealed||!secret||run.age<secret.age)return null;return{id:secret.id,kind:'secret',track:'origin',ageMin:secret.age,ageMax:105,icon:'⌂',text:`${secret.name}：${secret.text}`,effects:secret.effects,requirements:secret.requirements,actors:[],assertions:[],contentRevision:CONTENT_REVISION}}
  function eventWeight(event){const run=state.run;let weight=event.weight||10;if(event.track===run.mainConflict?.split('_')[0])weight*=1.2;if(event.track==='remote')weight*=1+run.capabilities.portableSkill*.12;if(event.track==='business')weight*=1+run.business.operatingSkill/180;if(event.track==='health'&&run.health.physical<50)weight*=1.6;if(event.track==='finance'&&(run.finance.totalDebt>0||run.pressures.money>50))weight*=1.6;if(event.track==='habits'&&run.habits.risk>30)weight*=1.5;if(event.track==='children'&&run.relationships.childCount)weight*=1.35;if(event.track==='partnership'&&run.relationships.partnerStatus!=='none')weight*=1.25;if(run.timeline.at(-1)?.track===event.track)weight*=.45;if(state.meta.seen.events[event.id])weight*=.75;return Math.max(.1,weight)}
  function selectBeat(run){const pool=INDEX.kinds.beat.filter(event=>eligible(event,run));return weighted(pool,eventWeight)}
  function activeArcDecision(run){for(const lane of['career','family','personal']){const arcId=run.arcSlots[lane];if(!arcId)continue;const record=run.arcs[arcId],candidate=INDEX.kinds.decision.find(event=>event.arc?.id===arcId&&event.arc.node===record.nextNode&&!run.usedEvents.includes(event.id));if(!candidate)continue;if(eligible(candidate,run))return candidate;if(run.age<candidate.ageMin)continue;if(run.age>candidate.ageMax||!requirementsMatch(candidate.requirements,run)||!resolveActors(candidate,run))invalidateArc(candidate)}return null}
  function mandatoryDecision(run){const globals=INDEX.kinds.decision.filter(event=>!event.arc&&eligible(event,run)),hasClaimedDesire=Object.values(run.desires).some(value=>value&&typeof value==='object'&&value.claimed);if(run.age>=14&&!hasClaimedDesire){const event=globals.find(item=>item.id==='decision_097');if(event)return event}if(run.age>=15&&run.age<=17&&run.education.level===2){const event=globals.find(item=>item.id==='decision_098');if(event)return event}if(run.age>=18&&run.age<=22&&run.education.status==='completed'&&run.employment.status==='none'){const event=globals.find(item=>item.id==='decision_099');if(event)return event}return globals.find(item=>item.id==='decision_100')||null}
  function crisisDecision(run){const track=run.finance.totalDebt>Math.max(50000,run.finance.lastIncome*1.5)?'finance':run.health.physical<35?'health':run.habits.stage==='dependent'?'habits':['none','unemployed'].includes(run.employment.status)&&run.activity.mode==='seeking'&&run.activity.years>=2?'employment':null;if(!track)return null;return weighted(INDEX.kinds.decision.filter(event=>event.track===track&&eligible(event,run)),eventWeight)}
  function startDecision(run){const active=activeArcDecision(run),forced=mandatoryDecision(run),crisis=crisisDecision(run);if(active||forced||crisis)return active||forced||crisis;const starts=INDEX.kinds.decision.filter(event=>event.arc?.role==='start'&&eligible(event,run));return weighted(starts,eventWeight)||weighted(INDEX.kinds.decision.filter(event=>eligible(event,run)),eventWeight)}
  function shouldOfferDecision(run){if(run.decisionCount>=run.targetDecisions)return false;if(mandatoryDecision(run)||activeArcDecision(run)||crisisDecision(run))return true;if(run.age-run.lastDecisionAge<2)return false;const remaining=Math.max(1,(run.naturalDeathAge-run.age)/4),needed=run.targetDecisions-run.decisionCount;return chance(Math.min(.55,needed/remaining*.35))}

  function addTimeline(event,text,variant='event'){const run=state.run;run.timeline.push({id:event.id,age:run.age,year:2026+run.age,kind:event.kind,track:event.track,icon:event.icon||'·',text,variant});run.timeline=run.timeline.slice(-180);state.meta.seen.events[event.id]=(state.meta.seen.events[event.id]||0)+1}
  function revealEvent(event){const run=state.run;applyCommands(event.runtimeEffects||event.effects||[],event);for(const tag of event.runtimeTags||[])addTag(run,tag);addTimeline(event,event.runtimeText||event.text);run.usedEvents.push(event.id);if(event.kind==='secret')run.secretRevealed=true;if(event.scheduleId){const schedule=run.scheduledConsequences.find(item=>item.id===event.scheduleId);if(schedule)schedule.status='used';run.usedConsequences.push(event.scheduleId)}save();render()}
  function beginYear(){
    const run=state.run;if(run.age>105||mortality(run)){finishLife();return true}educationMilestones(run);updatePeople(run);run.yearStarted=true;run.yearQueue=[];
    const dueCard=[0,18,35,55].find(age=>run.age>=age&&!run.cardAges.includes(age));if(dueCard!==undefined){startCardDraw(dueCard);return true}
    const special=dueConsequence(run)||dueSecret(run),primary=selectBeat(run)||{id:`quiet_${run.age}`,kind:'beat',track:'ordinary',icon:'·',text:'这一年没有大事，日子仍按自己的速度往前。',effects:[]};run.yearQueue.push(primary);if(special)run.yearQueue.push(special);else if(chance(.18)){const second=selectBeat(run);if(second&&second.id!==primary.id)run.yearQueue.push(second)}
    const rate=run.age<18?.004:run.age<65?.008:.006;if(run.swanCount<2&&run.age-run.lastSwanAge>=10&&chance(rate)){const swan=weighted(INDEX.kinds.blackSwan.filter(event=>eligible(event,run)),eventWeight);if(swan){run.yearQueue[Math.min(1,run.yearQueue.length-1)]=swan;run.swanCount++;run.lastSwanAge=run.age}}run.yearQueue=run.yearQueue.slice(0,2);return false
  }
  function finishYear(){const run=state.run;if(shouldOfferDecision(run)){const event=startDecision(run);if(event){run.currentDecision=event;run.phase='decision';save();render();return true}}settleYear(run);run.yearStarted=false;run.age++;syncDerived(run);save();return false}
  function advanceOneBeat(force=false){const run=state.run;if(!run||run.phase!=='playing'||(!force&&state.view!=='game')||inputLocked)return false;if(!force)inputLocked=true;try{for(let guard=0;guard<6;guard++){if(!run.yearStarted&&beginYear())return true;if(run.phase!=='playing')return true;if(run.yearQueue.length){revealEvent(run.yearQueue.shift());return true}if(finishYear())return true}return false}finally{if(!force)setTimeout(()=>inputLocked=false,150)}}

  function startCardDraw(age){const kind=age===0?'innate':'stage',pool=DATA.cards.filter(card=>card.kind===kind&&!state.run.cards.includes(card.id));state.run.phase='card';state.run.cardAge=age;state.run.cardOptions=[...pool].sort((a,b)=>stable(state.run.seed,`${age}:${a.id}`,100)-stable(state.run.seed,`${age}:${b.id}`,100)).slice(0,3);save();render()}
  function chooseCard(id){const run=state.run,card=INDEX.cards.get(id);if(!card||run.phase!=='card')return;run.cards.push(card.id);run.cardAges.push(run.cardAge);applyCommands(card.effects,card);addTimeline({id:card.id,kind:'card',track:'identity',icon:'◇'},`你保留了“${card.displayName}”：${card.text}`,'chosen');run.phase=run.cardAge===0?'playing':'playing';run.cardOptions=[];run.yearStarted=false;save();render()}

  function unlockCodex(){const run=state.run;for(const entry of DATA.codex){if(state.meta.codex.includes(entry.id))continue;const rule=entry.unlockRules||{},tagOk=rule.outcomeTagsAny?.some(tag=>run.outcomeTags[tag]),anyOk=rule.stateAny?.some(item=>predicateMatches(item,run)),allOk=rule.stateAll?.every(item=>predicateMatches(item,run));if(tagOk||anyOk||allOk)state.meta.codex.push(entry.id)}}

  function finalSignals(run){const signals=new Set(Object.keys(run.outcomeTags));signals.add('lifeEnded');if(new Set(run.decisionHistory.map(item=>item.eventId)).size>=2)signals.add('decisionDiversity');if(run.desires.peace.fulfillment>=65)signals.add('peace');if(run.finance.totalDebt===0&&run.finance.cash>=30000)signals.add('stable');if(run.desires.freedom.fulfillment>=65)signals.add('freedom');if(run.business.equity>=1e12)signals.add('wealthApex');if(run.finance.totalDebt>=1e6)signals.add('debtCrisis');if(run.habits.stage==='recovery'&&run.habits.recoveryYears>=3)signals.add('recovery');if(run.age<45)signals.add('earlyDeath');if(run.health.physical<40)signals.add('health');return signals}
  function endingProfile(run){const signals=finalSignals(run),fallback=DATA.endingProfiles.find(profile=>profile.id==='ordinaryContent')||DATA.endingProfiles[0],rarity={常见:1,少见:2,罕见:3,极罕:4,传奇:5},exact=DATA.endingProfiles.filter(profile=>profile.id!==fallback.id&&profile.signals.every(signal=>signals.has(signal))).sort((a,b)=>(rarity[b.rarity]||0)-(rarity[a.rarity]||0)||stable(run.seed,a.id,100)-stable(run.seed,b.id,100));if(exact.length)return exact[0];return fallback.signals.every(signal=>signals.has(signal))?fallback:DATA.endingProfiles.find(profile=>profile.id==='earlyExit'&&profile.signals.every(signal=>signals.has(signal)))||fallback}
  function endingAxes(run){const claimed=Object.values(run.desires).filter(value=>value&&typeof value==='object'&&value.claimed),fulfillment=(claimed.length?claimed:Object.values(run.desires).filter(value=>value&&typeof value==='object').sort((a,b)=>b.drive-a.drive).slice(0,3)).reduce((sum,item)=>sum+item.fulfillment,0)/(claimed.length||3);const support=(run.relationships.network+run.relationships.originBond+Math.max(0,run.relationships.partnerBond)+Math.max(0,run.relationships.childBond))/4,safety=clamp(50+Math.log10(Math.max(1,Math.abs(run.finance.netWorth)))*8-(run.finance.totalDebt>run.finance.lastIncome?25:0),0,100),impact=clamp(run.business.scale==='global'?100:run.business.scale==='national'?85:run.employment.rank*12+run.capabilities.skill*4+Object.keys(run.outcomeTags).length,0,100);return{自主:clamp(45+run.agency*1.5-run.pressures.family/3,0,100),关系:clamp(support,0,100),健康:clamp((run.health.physical+run.health.mental)/2,0,100),安全:safety,欲望兑现:clamp(fulfillment,0,100),社会影响:impact}}
  function pivotalFacts(run){const decisions=[...run.decisionHistory].sort((a,b)=>b.impact-a.impact||a.age-b.age).slice(0,3).sort((a,b)=>a.age-b.age).map(item=>({age:item.age,title:item.choice,result:item.result,source:item.eventId}));const used=new Set(decisions.map(item=>`${item.age}:${item.source}`));for(const item of run.timeline.filter(item=>['blackSwan','secret','consequence'].includes(item.kind)).reverse()){if(decisions.length>=3)break;const key=`${item.age}:${item.id}`;if(!used.has(key)){decisions.push({age:item.age,title:item.text,result:'这件事改变了之后可选的道路。',source:item.id});used.add(key)}}const realFallbacks=[{age:0,title:`出生在${run.location.name}的${run.originHousehold.familyName}`,result:'出身决定了最初的资源、关系和机会面。',source:'origin'},{age:0,title:`原生家庭有${run.originHousehold.people.filter(item=>item.relation==='sibling').length}名兄弟姐妹`,result:`家庭住房为${run.originHousehold.housing}，家庭债务约${money(run.originHousehold.debt)}。`,source:'origin-household'},{age:run.age,title:`生命因${run.deathCause||'自然衰老'}结束`,result:'生命长度也是这次种子真实形成的结果。',source:'death'}];for(const item of realFallbacks){if(decisions.length>=3)break;if(!used.has(`${item.age}:${item.source}`))decisions.push(item)}return decisions.slice(0,3).sort((a,b)=>a.age-b.age)}
  function routeTags(run){const labels={business:'经营者',remote:'远程迁移',leisure:'主动不工作',public:'公共职业',habits:'恢复者',children:'代际关系',finance:'债务人生',partnership:'亲密关系',health:'健康危机',employment:'受雇工作'};return Object.entries(labels).map(([track,label])=>({track,label,count:Object.keys(run.outcomeTags).filter(tag=>tag.startsWith(`${track}:`)).reduce((sum,tag)=>sum+run.outcomeTags[tag],0)})).filter(item=>item.count>0).sort((a,b)=>b.count-a.count).slice(0,3).map(item=>item.label)}
  function finishLife(){
    const run=state.run;if(run.phase==='ended'&&run.ending){state.view='ending';render();return}run.phase='ended';run.age=clamp(run.age,0,105);syncDerived(run);unlockCodex();const profile=endingProfile(run),titles=DATA.endingTitles.filter(title=>title.profileId===profile.id),title=titles[stable(run.seed,`ending:${profile.id}`,titles.length)]||titles[0],facts=pivotalFacts(run),axes=endingAxes(run);
    run.ending={profileId:profile.id,title:title?.title||'这一生',summary:profile.summary,rarity:profile.rarity,basis:[...profile.signals],axes,facts,tags:routeTags(run),seed:run.seed,age:run.age,deathCause:run.deathCause||'自然衰老',netWorth:run.finance.netWorth};
    state.meta.stats.runs=(state.meta.stats.runs||0)+1;state.meta.histories.unshift({title:run.ending.title,profileId:profile.id,rarity:profile.rarity,age:run.age,seed:run.seed,familyId:run.originHousehold.familyId,familyName:run.originHousehold.familyName,tags:run.ending.tags,axes,endedAt:Date.now()});state.meta.histories=state.meta.histories.slice(0,40);state.meta.recentSeeds.unshift(run.seed);state.meta.recentSeeds=state.meta.recentSeeds.slice(0,8);state.view='ending';save(true);render()
  }

  function topDesires(run=state.run){return Object.entries(run.desires).filter(([,value])=>value&&typeof value==='object').map(([key,value])=>({key,...value})).sort((a,b)=>Number(b.claimed)-Number(a.claimed)||b.drive-a.drive).slice(0,3)}
  function pressureLevel(run=state.run){const value=Math.max(...Object.values(run.pressures));return value>=80?'危机':value>=60?'严重':value>=30?'明显':'可控'}
  function educationLabel(run){const paths={primary:'小学',middleSchool:'初中',highSchool:'高中',vocational:'职业教育',college:'大学',postgraduate:'研究生'},fallback=['未入学','小学','初中','高中', '大学','研究生'],name=paths[run.education.path]||fallback[run.education.level]||'未入学';return`${name}${run.education.status==='enrolled'?'在读':run.education.status==='interrupted'?'中断':run.education.level?'毕业':''}`}
  function activityLabel(run){return{childhood:'童年',study:'学习',work:'工作',seeking:'求职',care:'照护',sabbatical:'计划休息',leisure:'不工作',retired:'退休',flexible:'灵活安排'}[run.activity.mode]||run.activity.mode}
  function employmentLabel(run){return{none:'未进入劳动市场',employed:'受雇工作',gig:'灵活就业',selfEmployed:'自主经营',unemployed:'求职中',retired:'已退休',careLeave:'照护离岗'}[run.employment.status]||run.employment.status}
  function housingLabel(run){return{family:'与原生家庭同住',renting:'租住',owned:'自有住房',mortgaged:'按揭住房',supported:'由家人或伴侣提供',unstable:'临时住所'}[run.housing.status]||run.housing.status}
  function habitLabel(run){return{none:'无持续问题',exposed:'接触',repeating:'反复',dependent:'依赖',uncontrolled:'失控',treatment:'治疗中',recovery:'恢复中',relapse:'复发'}[run.habits.stage]||run.habits.stage}
  function roleLine(run){const job=run.employment.status==='employed'?run.employment.career:activityLabel(run),partner={none:'单身',dating:'恋爱中',partnered:'稳定伴侣',married:'已婚',separated:'分居',divorced:'离异',widowed:'丧偶'}[run.relationships.partnerStatus];return`${job} · ${partner} · ${run.relationships.childCount?`${run.relationships.childCount}名子女`:'无子女'}`}

  function homeView(){const active=state.run&&state.run.phase!=='ended';return`<main class="screen center"><span class="version">v${VERSION}</span><div><h1>人生尚未加载</h1><p class="hero-sub">出生决定最初能看见的门，之后每一步都会改变下一扇门。</p></div>${state.meta.migrationNotice?'<section class="card migration-note"><strong>游戏内容已经更新</strong><p class="tiny">旧版本的活动人生已结束；人生档案、图鉴、设置和跨局记录仍被保留。</p></section>':''}${state.recovery?`<section class="card migration-note"><strong>存档已重置</strong><p class="tiny">${esc(state.recovery.message)}</p></section>`:''}<div class="mt stack">${active?'<button class="btn primary" data-act="continue">继续这一生</button>':'<button class="btn primary" data-act="new">开始新人生</button>'}<div class="menu-list"><button class="menu-item" data-nav="archive"><strong>人生档案</strong><span>›</span></button><button class="menu-item" data-nav="codex"><strong>社会图鉴</strong><span>›</span></button><button class="menu-item" data-nav="settings"><strong>设置</strong><span>›</span></button></div></div><p class="tiny">离线运行 · 自动存档</p></main>`}
  function birthView(){const run=state.run,origin=run.originHousehold,parents=origin.people.filter(item=>['father','mother'].includes(item.relation)),siblings=origin.people.filter(item=>item.relation==='sibling'&&item.bornAt<=0);return`<main class="screen"><div class="topbar"><button class="iconbtn" data-nav="home">‹</button><div class="title">出生信息</div><span></span></div><section class="card hero"><div class="muted">${run.gender==='female'?'女性':'男性'} · ${run.location.name}</div><div class="birth-place">${esc(origin.familyName)}</div><p>家庭资产、债务与住房属于原生家庭，不自动算作你的个人财产。</p><p class="tiny origin-hint">起点优势：${esc(DATA.familyArchetypes.find(item=>item.id===origin.familyId)?.advantages.join(' · '))} · 潜在压力：${esc(DATA.familyArchetypes.find(item=>item.id===origin.familyId)?.risks.join(' · '))}</p></section><dl class="spec-list"><div class="spec"><dt>父母</dt><dd>${parents.map(item=>`${item.relation==='father'?'父亲':'母亲'}：${item.occupation}`).join('；')||'由其他照护者抚养'}</dd></div><div class="spec"><dt>兄弟姐妹</dt><dd>${siblings.length?`${siblings.length}人`:'目前没有'}</dd></div><div class="spec"><dt>家庭住房</dt><dd>${esc(origin.housing)}</dd></div><div class="spec"><dt>家庭账面</dt><dd>资产约 ${money(origin.assets)} · 债务约 ${money(origin.debt)}</dd></div></dl><div class="bottom-actions"><button class="btn primary" data-act="birth-next">塑造初始属性</button></div></main>`}
  const attrMeta={intellect:['理解','学习、证据与复杂判断'],physique:['体魄','恢复、疾病与劳动承受'],looks:['外貌','初见与被看见的机会'],stability:['稳定','现金流、节奏与压力控制'],social:['社交','关系、协商与支持网络'],ambition:['野心','职业、财富与风险承受']};
  function attributesView(){const run=state.run;return`<main class="screen attributes-screen"><div class="topbar"><button class="iconbtn" data-act="attributes-back">‹</button><div class="title">初始塑形</div><span></span></div><div class="remain"><div class="row"><span class="muted">剩余点数</span><b class="big-number">${run.points}</b></div><p class="tiny">出生不可选择，但你可以决定最初更依赖什么。</p></div><section class="card">${Object.entries(attrMeta).map(([key,[name,desc]])=>`<div class="attr-row"><div><div class="attr-name">${name}</div><div class="attr-desc">${desc}</div></div><div class="stepper"><button data-attr="${key}" data-delta="-1">−</button><b>${run.attrs[key]}</b><button data-attr="${key}" data-delta="1">＋</button></div></div>`).join('')}</section><div class="bottom-actions attributes-actions"><button class="btn ghost" data-act="random-attributes">随机分配</button><button class="btn primary" data-act="attributes-done" ${run.points?'disabled':''}>确认这一组属性</button></div></main>`}
  function streamRows(run){if(!run.timeline.length)return'<div class="stream-empty">轻触这里，让第一年开始。</div>';return run.timeline.slice(-12).map(item=>`<div class="stream-row ${item.variant==='chosen'?'chosen':''}"><span class="stream-age">${item.age}岁</span><span class="stream-icon">${item.icon||'·'}</span><div><p>${esc(item.text)}</p><div class="stream-hints"><span>${esc(TRACK_LABELS[item.track]||'生活')}</span>${item.kind==='consequence'?'<span>旧事回响</span>':''}</div></div></div>`).join('')}
  function choiceSheet(event){const actors=resolveActors(event)||{};return`<div class="modal-wrap locked-modal"><section class="choice-sheet"><div class="handle"></div><div class="decision-emoji">${event.icon||'◎'}</div><h2>${esc(event.prompt)}</h2>${Object.keys(actors).length?`<p>这次涉及：${Object.values(actors).map(item=>item.relation==='partner'?'伴侣':item.relation.includes('child')?'子女':'家人').join('、')}</p>`:''}<div class="choices">${event.choices.map((choice,index)=>`<button class="choice" data-choice="${index}">${esc(choice.text)}<small>${esc(choice.hints?.join(' · ')||'')}</small></button>`).join('')}</div></section></div>`}
  function cardSheet(run){return`<div class="modal-wrap locked-modal"><section class="choice-sheet card-sheet"><div class="handle"></div><h2>这一阶段，你保留哪一种能力？</h2><div class="choices">${run.cardOptions.map(card=>`<button class="choice clear-card" data-card="${card.id}"><span class="omen-icon">◇</span><span><span class="fate-title">${esc(card.displayName)}</span><span class="fate-text">${esc(card.text)}</span></span><span>›</span></button>`).join('')}</div></section></div>`}
  function statusDrawer(run){const partner={none:'单身',dating:'恋爱中',partnered:'稳定伴侣',married:'已婚',separated:'分居',divorced:'离异',widowed:'丧偶'}[run.relationships.partnerStatus],liabilities=run.finance.liabilities.filter(item=>item.status!=='settled');return`<div class="drawer-wrap" data-act="close-drawer"><section class="drawer" data-stop><div class="handle"></div><div class="row"><div><div class="eyebrow">${run.age}岁 · ${run.world.year}年</div><div class="sheet-title">${esc(run.originHousehold.familyName)}</div></div><button class="iconbtn" data-act="close-drawer">×</button></div><div class="section-title">现在的生活</div><dl class="spec-list"><div class="spec"><dt>学历</dt><dd>${educationLabel(run)}</dd></div><div class="spec"><dt>主要活动</dt><dd>${activityLabel(run)}</dd></div><div class="spec"><dt>工作</dt><dd>${run.employment.status==='employed'?`${run.employment.career} · ${money(baseSalary(run))}/年`:employmentLabel(run)}</dd></div><div class="spec"><dt>婚恋</dt><dd>${partner} · 关系 ${Math.round(run.relationships.partnerBond)}</dd></div><div class="spec"><dt>子女</dt><dd>${run.relationships.childCount?childPeople(run).map(child=>`${personAge(child,run)}岁`).join('、'):'无'}</dd></div><div class="spec"><dt>住房</dt><dd>${housingLabel(run)}</dd></div><div class="spec"><dt>个人净值</dt><dd>${money(run.finance.netWorth)}</dd></div><div class="spec"><dt>债务</dt><dd>${liabilities.length?`${liabilities.length}笔 · ${money(run.finance.totalDebt)}`:'无'}</dd></div><div class="spec"><dt>身体／精神</dt><dd>${Math.round(run.health.physical)}／${Math.round(run.health.mental)}</dd></div><div class="spec"><dt>习惯状态</dt><dd>${habitLabel(run)}</dd></div><div class="spec"><dt>压力</dt><dd>${pressureLevel(run)}</dd></div></dl><div class="section-title">最在意的事</div><div class="desire-list">${topDesires(run).map(item=>`<span>${esc(item.name)} ${item.claimed?'· 已认领':''} · ${Math.round(item.fulfillment)}</span>`).join('')}</div><div class="section-title">正在延续</div><div class="taglist left">${Object.values(run.arcs).filter(item=>item.status==='active').map(item=>`<span class="pill">${esc(TRACK_LABELS[item.id.split('_')[0]]||item.id)}</span>`).join('')||'<span class="tiny">没有未完成的连续路线</span>'}</div></section></div>`}
  function gameView(){const run=state.run;return`<main class="screen stream-screen"><header class="game-header"><div class="row"><div><div class="age">${run.age}岁</div><div class="role">${esc(roleLine(run))}</div></div><button class="iconbtn" data-act="open-drawer">☰</button></div><div class="resource-strip"><div class="res"><span>现金</span><b>${money(run.finance.cash)}</b></div><div class="res"><span>净值</span><b>${money(run.finance.netWorth)}</b></div><div class="res"><span>身体</span><b>${Math.round(run.health.physical)}</b></div><div class="res"><span>精神</span><b>${Math.round(run.health.mental)}</b></div></div></header><div class="conflict-line">核心矛盾 · ${esc(DATA.conflicts.find(item=>item.id===run.mainConflict)?.name||'还没有答案')}</div><div class="life-stream" tabindex="0" data-act="advance">${streamRows(run)}<div class="stream-cursor"><i></i>轻触推进一条人生事件</div></div>${DEBUG?`<div class="debug-panel">debug · seed ${esc(run.seed)} · choices ${run.decisionCount}/${run.targetDecisions}</div>`:''}</main>${run.phase==='decision'?choiceSheet(run.currentDecision):''}${run.phase==='card'?cardSheet(run):''}${state.drawer?statusDrawer(run):''}`}

  function endingView(){const run=state.run,e=run.ending;return`<main class="screen ending-screen"><div class="ending-share-card"><div class="eyebrow ending-kicker">人生尚未加载 · 2026</div><div class="lifespan">活到 <b>${e.age}</b> 岁</div><div class="ending-title">《${esc(e.title)}》</div><p class="ending-review sharp-summary">${esc(e.summary)}</p><div class="ending-rarity"><span class="pill rare">人生稀有度 · ${esc(e.rarity)}</span><span class="pill">种子 ${esc(e.seed)}</span></div><div class="section-title">三个真实转折</div><section class="card timeline">${e.facts.map(item=>`<div class="time-item"><span class="time-age">${item.age}岁</span><div><strong>${esc(item.title)}</strong><p class="tiny">${esc(item.result)}</p></div></div>`).join('')}</section><div class="taglist">${e.tags.map(tag=>`<span class="pill">${esc(tag)}</span>`).join('')||'<span class="pill">未归类人生</span>'}</div></div><div class="section-title">这一生的六个维度</div><section class="card ending-portrait">${Object.entries(e.axes).map(([name,value])=>`<div class="portrait-row"><div class="row"><span>${name}</span><b>${Math.round(value)}</b></div><div class="meter"><i style="width:${clamp(value,0,100)}%"></i></div></div>`).join('')}</section><section class="card soft mt"><div class="spec"><dt>最终净值</dt><dd>${money(e.netWorth)}</dd></div><div class="spec"><dt>死亡原因</dt><dd>${esc(e.deathCause)}</dd></div><div class="spec"><dt>亲手选择</dt><dd>${run.decisionCount} 次</dd></div></section><div class="stack mt"><button class="btn primary" data-act="new">立即重开</button><button class="btn ghost" data-nav="archive">查看人生档案</button></div></main>`}
  function archiveView(){const all=[...state.meta.histories,...state.meta.legacyHistories];return`<main class="screen"><div class="topbar"><button class="iconbtn" data-nav="home">‹</button><div class="title">人生档案</div><span></span></div><section class="card">${all.length?all.map(item=>`<div class="archive-item"><div class="archive-title">《${esc(item.title||'旧人生')}》</div><div class="archive-meta">${item.age??'?'}岁 · ${esc(item.rarity||'旧版本')} · ${esc(item.familyName||'历史档案')}${item.seed?` · ${esc(item.seed)}`:''}</div></div>`).join(''):'<p>还没有完整走完的人生。</p>'}</section></main>`}
  function codexView(){return`<main class="screen"><div class="topbar"><button class="iconbtn" data-nav="home">‹</button><div class="title">社会图鉴 ${state.meta.codex.length}/${DATA.codex.length}</div><span></span></div><section class="card">${DATA.codex.map(item=>{const unlocked=state.meta.codex.includes(item.id);return`<div class="codex-item ${unlocked?'':'locked'}"><span class="codex-category">${esc(item.category)}</span><h3>${unlocked?esc(item.name):'尚未发现'}</h3><p>${unlocked?'这项现实已经由本局状态或选择真实解锁。':esc(item.lockedHint)}</p></div>`}).join('')}</section></main>`}
  function settingsView(){return`<main class="screen"><div class="topbar"><button class="iconbtn" data-nav="home">‹</button><div class="title">设置</div><span></span></div><section class="card"><button class="menu-item" data-act="toggle-haptic"><strong>轻触反馈</strong><span class="switch ${state.meta.settings.haptic?'on':''}"><i></i></span></button><button class="menu-item" data-act="export"><strong>导出存档</strong><span>›</span></button><button class="menu-item" data-act="clear-data"><strong class="danger-text">清除全部数据</strong><span>›</span></button></section><p class="tiny mt">版本更新只保留人生档案、图鉴、设置和跨局记录，不延续旧版本的活动人生。</p></main>`}

  function render(){if(!state)return;const views={home:homeView,birth:birthView,attributes:attributesView,game:gameView,ending:endingView,archive:archiveView,codex:codexView,settings:settingsView};if(state.run?.phase==='ended'&&state.view==='game')state.view='ending';app.innerHTML=(views[state.view]||homeView)();requestAnimationFrame(()=>{const stream=app.querySelector('.life-stream');if(stream)stream.scrollTop=stream.scrollHeight})}
  function showToast(message){document.querySelector('.toast')?.remove();const element=document.createElement('div');element.className='toast';element.textContent=message;document.body.append(element);setTimeout(()=>element.remove(),1800)}
  function haptic(duration=12){if(state.meta.settings.haptic&&navigator.vibrate)navigator.vibrate(duration)}
  function exportSave(){const blob=new Blob([JSON.stringify({schemaVersion:SCHEMA_VERSION,gameVersion:VERSION,meta:state.meta,run:state.run},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='人生尚未加载-v5.0.2-存档.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
  function clearAllData(){if(!window.confirm('确定清除全部数据？人生档案、图鉴、设置、当前人生和旧版本遗留数据都会删除，且无法恢复。'))return;for(const key of gameStorageKeys())localStorage.removeItem(key);state=null;location.reload()}
  function newLife(){state.run=createRun();state.view='birth';state.drawer=false;save(true);render()}
  function syncInitialCapabilities(run){run.capabilities.portableSkill=Math.max(run.originHousehold.digitalLiteracy>=60?1:0,Math.floor((run.attrs.intellect-1)/3));run.capabilities.employability=clamp(40+run.attrs.stability*3+run.attrs.social*2,0,100)}
  function changeAttribute(key,delta){const run=state.run,current=run.attrs[key];if(delta>0&&run.points>0&&current<10){run.attrs[key]++;run.points--}if(delta<0&&current>1){run.attrs[key]--;run.points++}syncInitialCapabilities(run);render()}
  function randomizeAttributes(){const run=state.run,keys=Object.keys(run.attrs);for(const key of keys)run.attrs[key]=1;run.points=20;while(run.points){const available=keys.filter(key=>run.attrs[key]<10),key=available[Math.floor(rng()*available.length)];run.attrs[key]++;run.points--}syncInitialCapabilities(run);haptic(8);save();render()}
  function handleAction(name){if(name==='new')newLife();else if(name==='continue'){state.view='game';render()}else if(name==='birth-next'){state.run.phase='attributes';state.view='attributes';save();render()}else if(name==='attributes-back'){state.run.phase='birth';state.view='birth';render()}else if(name==='random-attributes')randomizeAttributes();else if(name==='attributes-done'&&!state.run.points){state.view='game';startCardDraw(0)}else if(name==='advance')advanceOneBeat();else if(name==='open-drawer'){state.drawer=true;render()}else if(name==='close-drawer'){state.drawer=false;render()}else if(name==='toggle-haptic'){state.meta.settings.haptic=!state.meta.settings.haptic;save();render()}else if(name==='export')exportSave();else if(name==='clear-data')clearAllData()}
  app.addEventListener('click',event=>{if(event.target.closest('[data-stop]')&&event.target.closest('[data-act="close-drawer"]')===null)event.stopPropagation();const choice=event.target.closest('[data-choice]');if(choice){chooseDecision(Number(choice.dataset.choice));return}const card=event.target.closest('[data-card]');if(card){chooseCard(card.dataset.card);return}const attr=event.target.closest('[data-attr]');if(attr){changeAttribute(attr.dataset.attr,Number(attr.dataset.delta));return}const action=event.target.closest('[data-act]');if(action){handleAction(action.dataset.act);return}const nav=event.target.closest('[data-nav]');if(nav){state.view=nav.dataset.nav;state.drawer=false;render()}});
  app.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-act="advance"]')){event.preventDefault();advanceOneBeat()}});

  function patchRun(patch){if(!state.run)return null;for(const[key,value]of Object.entries(patch||{})){if(value&&typeof value==='object'&&!Array.isArray(value)&&state.run[key]&&typeof state.run[key]==='object')state.run[key]={...state.run[key],...copy(value)};else state.run[key]=copy(value)}state.run=normalizeRun(state.run);save(true);render();return copy(state.run)}
  function forceDecision(id){const event=INDEX.event.get(id);if(!state.run||event?.kind!=='decision')return null;state.run.age=Math.max(event.ageMin,Math.min(event.ageMax,state.run.age));if(event.track==='remote')state.run.capabilities.portableSkill=Math.max(1,state.run.capabilities.portableSkill);if(event.track==='business')state.run.finance.cash=Math.max(20000,state.run.finance.cash);if(event.track==='public')state.run.education.level=Math.max(3,state.run.education.level);if(event.track==='children'&&event.actors?.some(actor=>actor.relation==='child'||actor.relationAny?.includes('child'))&&!childPeople(state.run).length)createRelatedPerson(state.run,{relation:'child'});if(event.track==='partnership'&&event.arc?.node>1&&!partnerPeople(state.run).length){state.run.people.push(person('partner','partner',state.run.age-2,{bond:60}));state.run.relationships.partnerStatus='partnered'}state.run.currentDecision=event;state.run.phase='decision';state.run.yearStarted=true;state.view='game';render();return event.id}
  function renderGameToText(){const run=state.run;return JSON.stringify({view:state.view,version:VERSION,run:run?{phase:run.phase,age:run.age,year:run.world.year,seed:run.seed,education:run.education,activity:run.activity,employment:run.employment,finance:{cash:run.finance.cash,totalDebt:run.finance.totalDebt,netWorth:run.finance.netWorth,liabilities:run.finance.liabilities},relationships:{partnerStatus:run.relationships.partnerStatus,children:childPeople(run).map(child=>personAge(child,run)),livingPeople:run.people.filter(item=>item.alive).map(item=>({id:item.id,relation:item.relation,age:personAge(item,run)}))},health:run.health,habits:run.habits,mobility:run.mobility,business:run.business,activeArcs:Object.values(run.arcs).filter(item=>item.status==='active'),scheduledConsequences:run.scheduledConsequences.filter(item=>item.status==='scheduled'),decisionCount:run.decisionCount,decision:run.currentDecision?{id:run.currentDecision.id,prompt:run.currentDecision.prompt,choices:run.currentDecision.choices.map((choice,index)=>({index,text:choice.text,memoryKey:choice.memoryKey}))}:null,visibleTimeline:run.timeline.slice(-6),ending:run.ending}:null})}
  window.render_game_to_text=renderGameToText;window.advanceTime=()=>renderGameToText();

  app.innerHTML='<main class="loading-screen"><div><div class="loading-mark">◌</div><h2>正在加载人生账本</h2><p>每一步都会留下依据。</p></div></main>';
  fetch(`./data.json?v=${VERSION}`,{cache:'no-store'}).then(response=>{if(!response.ok)throw new Error(`人生数据库加载失败（HTTP ${response.status}）`);return response.json()}).then(data=>{DATA=data;if(DATA.schemaVersion!==SCHEMA_VERSION)throw new Error(`数据版本不兼容：需要 ${SCHEMA_VERSION}，实际 ${DATA.schemaVersion}`);INDEX=buildIndex();state=loadState();render();window.__LIFE_BOOTED__=true;if(DEBUG)window.__LIFE_DEBUG__={snapshot:()=>copy(state.run),advance:()=>advanceOneBeat(true),forceAge:age=>patchRun({age:clamp(age,0,105),yearStarted:false,yearQueue:[]}),forceDecision,patchRun,eligibleIds:kind=>(INDEX.kinds[kind]||[]).filter(event=>eligible(event)).map(event=>event.id),settleYear:()=>{settleYear(state.run);render();return copy(state.run)},finish:()=>{state.run.deathCause='调试结束';finishLife();return copy(state.run.ending)},counts:()=>Object.fromEntries(Object.entries(INDEX.kinds).map(([kind,items])=>[kind,items.length]))}}).catch(error=>{console.error(error);app.innerHTML=`<main class="boot-fallback"><div><div class="boot-label">启动失败</div><h1>人生数据库没有加载成功</h1><p>${esc(error.message||error)}</p></div><div class="boot-card"><p>请确认 index.html、style.css、game.js 与 data.json 位于同一目录。</p><button class="btn primary mt" onclick="location.reload()">重新加载</button></div></main>`});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&state?.run)save(true)});window.addEventListener('pagehide',()=>state?.run&&save(true));
})();
