const profile=(id,name,tier,sector,employerType,contractType,arrangement,incomeStability,salaryBand='mid',extra={})=>({
  id,name,tier,sector,employerType,contractType,arrangement,incomeStability,salaryBand,
  firstJobEligible:tier!=='T4',
  entryPaths:['openRecruitment'],
  regions:['tier1','tier2','county','town'],
  credentials:[],
  ...extra
});

export const EMPLOYMENT_CATALOG_SOURCE=Object.freeze({
  tiers:{
    T0:{label:'基础与零工',firstJobEligible:true,monthlyBase:4200},
    T1:{label:'熟练执行',firstJobEligible:true,monthlyBase:6000},
    T2:{label:'专业岗位',firstJobEligible:true,monthlyBase:12000},
    T3:{label:'高级专业与初级管理',firstJobEligible:true,monthlyBase:20000},
    T4:{label:'高层管理与成熟经营',firstJobEligible:false,monthlyBase:0}
  },
  regionalCoefficients:{tier1:1.2,tier2:1,county:.82,town:.72},
  salaryBands:{low:.9,mid:1,high:1.1},
  incomeModes:{
    fixed:{label:'固定月薪',annualMonths:12,range:[1,1]},
    fixedPlusBonus:{label:'月薪加奖金',annualMonths:13,range:[.92,1.08]},
    piecework:{label:'计件收入',annualMonths:12,range:[.8,1.2]},
    project:{label:'项目收入',annualMonths:12,range:[.7,1.3]},
    business:{label:'经营收入',annualMonths:0,range:[0,0]}
  },
  promotionMap:{
    store_clerk:'store_supervisor',
    software_engineer:'algorithm_engineer',
    research_specialist:'rd_engineer',
    rd_engineer:'department_executive',
    algorithm_engineer:'department_executive',
    investment_analyst:'firm_partner',
    junior_manager:'department_executive',
    lawyer:'firm_partner',
    university_lecturer:'professor'
  },
  profiles:[
    profile('crowd_rider','众包骑手','T0','platform','platform','platform','mobile','piecework','mid',{entryPaths:['platform','reentry']}),
    profile('station_rider','专送骑手','T0','services','platform','service','mobile','piecework','high',{entryPaths:['siteDirect','reentry']}),
    profile('warehouse_picker','仓储分拣员','T0','logistics','agency','dispatch','onsite','fixedPlusBonus','mid',{entryPaths:['agency','openRecruitment','reentry']}),
    profile('cleaning_worker','保洁员','T0','services','private','service','onsite','fixed','low',{entryPaths:['agency','directBoss','reentry']}),
    profile('loading_gig','装卸零工','T0','logistics','agency','dayLabor','onsite','project','high',{entryPaths:['agency','reentry']}),
    profile('store_clerk','门店店员','T0','retail','private','fixedTerm','splitShift','fixed','mid',{entryPaths:['storeDirect','openRecruitment','reentry']}),
    profile('food_hourly','餐饮小时工','T0','hospitality','private','hourly','splitShift','fixed','low',{entryPaths:['storeDirect','reentry']}),
    profile('factory_operator','工厂操作员','T1','manufacturing','private','fixedTerm','shift','fixedPlusBonus','mid',{entryPaths:['agency','openRecruitment','vocational','reentry']}),
    profile('store_supervisor','门店值班主管','T1','retail','private','fixedTerm','splitShift','fixedPlusBonus','mid',{entryPaths:['conversion','storeDirect','vocational','reentry']}),
    profile('customer_service','客服专员','T1','services','private','fixedTerm','shift','fixedPlusBonus','mid',{entryPaths:['openRecruitment','reentry']}),
    profile('admin_assistant','行政助理','T1','general','private','fixedTerm','onsite','fixed','mid',{entryPaths:['campus','openRecruitment','referral','reentry']}),
    profile('sales_representative','销售代表','T1','sales','private','fixedTerm','onsite','fixedPlusBonus','high',{entryPaths:['openRecruitment','directBoss','reentry']}),
    profile('skilled_technician','技能工','T1','manufacturing','private','fixedTerm','shift','fixedPlusBonus','high',{entryPaths:['vocational','conversion','reentry']}),
    profile('software_engineer','软件工程师','T2','digital','private','fixedTerm','hybrid','fixedPlusBonus','high',{entryPaths:['campus','specialist','conversion','reentry']}),
    profile('accountant','会计','T2','professional','private','fixedTerm','onsite','fixed','mid',{entryPaths:['campus','specialist','reentry']}),
    profile('engineering_specialist','工程专员','T2','professional','private','fixedTerm','onsite','fixedPlusBonus','mid',{entryPaths:['campus','specialist','conversion','reentry']}),
    profile('designer','设计师','T2','creative','private','project','hybrid','project','mid',{entryPaths:['specialist','openRecruitment','reentry']}),
    profile('legal_assistant','法务助理','T2','legal','private','fixedTerm','onsite','fixed','mid',{entryPaths:['campus','specialist','reentry']}),
    profile('research_specialist','研究项目专员','T2','research','private','project','hybrid','project','mid',{entryPaths:['specialist','campus','reentry']}),
    profile('rd_engineer','研发工程师','T3','research','private','fixedTerm','hybrid','fixedPlusBonus','mid',{entryPaths:['specialist','campus']}),
    profile('algorithm_engineer','算法工程师','T3','digital','private','fixedTerm','hybrid','fixedPlusBonus','high',{entryPaths:['specialist','campus']}),
    profile('investment_analyst','投研分析师','T3','finance','private','fixedTerm','onsite','fixedPlusBonus','high',{entryPaths:['specialist','campus']}),
    profile('junior_manager','初级部门经理','T3','management','private','fixedTerm','onsite','fixedPlusBonus','mid',{entryPaths:['managementTrainee','promotion']}),
    profile('doctor','医生','T3','medical','public','service','shift','fixedPlusBonus','mid',{entryPaths:['professionalQualification','specialist'],credentials:['medical_practice']}),
    profile('lawyer','律师','T3','legal','private','service','onsite','project','mid',{entryPaths:['professionalQualification','specialist'],credentials:['legal_practice']}),
    profile('university_lecturer','大学讲师','T3','education','public','service','onsite','fixedPlusBonus','low',{entryPaths:['professionalQualification','specialist'],credentials:['university_teaching']}),
    profile('public_clerk','公共部门职员','T2','public','public','service','onsite','fixedPlusBonus','mid',{firstJobEligible:false,entryPaths:['publicExam']}),
    profile('remote_contractor','远程项目承包者','T2','digital','platform','project','remote','project','mid',{entryPaths:['remoteContract','reentry']}),
    profile('small_shop_owner','小店经营者','T2','retail','self','business','onsite','business','mid',{firstJobEligible:false,entryPaths:['business']}),
    profile('department_executive','企业高管','T4','management','private','openEnded','onsite','fixedPlusBonus','high',{firstJobEligible:false,entryPaths:['promotion']}),
    profile('firm_partner','专业机构合伙人','T4','professional','partnership','business','hybrid','fixedPlusBonus','high',{firstJobEligible:false,entryPaths:['promotion','business']}),
    profile('professor','教授','T4','education','public','service','onsite','fixedPlusBonus','high',{firstJobEligible:false,entryPaths:['promotion'],credentials:['university_teaching']}),
    profile('mature_owner','成熟企业经营者','T4','management','self','business','onsite','business','high',{firstJobEligible:false,entryPaths:['business']})
  ],
  recruitmentScenarios:[
    {id:'E01',title:'门店夜班到面试才说',age:[16,24],tiers:['T0'],locations:['county'],applicationChannels:['openRecruitment','bridge'],entryPath:'storeDirect',profileIds:['store_clerk']},
    {id:'E02',title:'中介收费后说原厂已满',age:[16,24],tiers:['T0'],locations:['tier2'],applicationChannels:['openRecruitment','bridge'],entryPath:'agency',profileIds:['warehouse_picker','loading_gig']},
    {id:'E03',title:'只催到岗却不讲岗位',age:[18,24],tiers:['T1'],locations:['tier2'],applicationChannels:['openRecruitment','conversion'],entryPath:'openRecruitment',profileIds:['customer_service','sales_representative']},
    {id:'E04',title:'专业面通过后继续横向比较',age:[20,31],tiers:['T2','T3'],locations:['tier1'],applicationChannels:['openRecruitment','specialist'],entryPath:'specialist',profileIds:['software_engineer','accountant','engineering_specialist','designer','legal_assistant','research_specialist','doctor','lawyer','university_lecturer']},
    {id:'E05',title:'谈薪时索要工资流水',age:[20,31],tiers:['T2'],locations:['tier1'],applicationChannels:['openRecruitment','specialist'],entryPath:'openRecruitment',profileIds:['designer']},
    {id:'E06',title:'老板在店里直接面试',age:[18,31],tiers:['T1'],locations:['county'],applicationChannels:['openRecruitment','bridge'],entryPath:'directBoss',profileIds:['sales_representative']},
    {id:'E07',title:'高管终面临时增加出差要求',age:[22,31],tiers:['T3'],locations:['tier1'],applicationChannels:['specialist','conversion'],entryPath:'managementTrainee',profileIds:['junior_manager']},
    {id:'E08',title:'海外招聘先核工作授权',age:[20,31],tiers:['T2','T3'],applicationRegions:['us','europe'],applicationChannels:['specialist','openRecruitment'],entryPath:'specialist',profileIds:['software_engineer','engineering_specialist','research_specialist','rd_engineer','algorithm_engineer']},
    {id:'E09',title:'项目结束另行安排',age:[20,31],tiers:['T2'],locations:['tier2'],applicationChannels:['openRecruitment','specialist'],entryPath:'openRecruitment',profileIds:['designer','research_specialist']},
    {id:'E10',title:'要求三天无薪试岗',age:[18,31],tiers:['T1'],locations:['tier2'],applicationChannels:['openRecruitment','bridge'],entryPath:'openRecruitment',profileIds:['customer_service','sales_representative']},
    {id:'E11',title:'离职前要求背调现领导',age:[20,31],tiers:['T2'],locations:['tier1'],applicationChannels:['specialist'],entryPath:'specialist',profileIds:['software_engineer','accountant','engineering_specialist','designer','legal_assistant','research_specialist']},
    {id:'E12',title:'熟人介绍但合同发薪日不明',age:[18,31],tiers:['T1'],locations:['town'],applicationChannels:['openRecruitment','bridge'],entryPath:'referral',profileIds:['admin_assistant']},
    {id:'E13',title:'月入过万广告旁是租车合同',age:[16,31],tiers:['T0'],locations:['tier2'],applicationChannels:['openRecruitment','bridge'],entryPath:'platform',profileIds:['crowd_rider','station_rider']},
    {id:'E14',title:'约定反馈日只有自动通知',age:[16,31],tiers:['T0','T1','T2','T3'],applicationChannels:['openRecruitment','conversion','specialist','bridge'],entryPath:'openRecruitment'}
  ]
});
