const p = (path, op, value) => ({ path, op, value });
const req = (all = [], any = [], none = []) => ({ all, any, none });
const c = (type, target, value, extra = {}) => ({ type, target, value, ...extra });
const option = (text, resultText, echoText, effects = []) => ({ text, resultText, echoText, effects });

export const FABLE_BEATS = [
  ['beat_481','leisure','ordinary',[30,59],req(),'工作日上午的超市几乎没人，你把每个货架都走了一遍。'],
  ['beat_482','leisure','awkward',[30,59],req(),'同学群在聊学区房。你往上翻了翻，找到上一个自己说过话的位置。'],
  ['beat_483','leisure','friction',[30,55],req([p('activity.mode','in',['seeking','leisure'])]),'招聘要求里出现了一个你没见过的工具名。你查了一下，教程第一课是注册账号。'],
  ['beat_484','leisure','pressure',[32,58],req([p('pressures.money','gte',45)]),'体检套餐你选了基础版，勾选框上面那行小字你读了两遍。'],
  ['beat_485','housing','ordinary',[30,59],req([p('housing.status','eq','renting')]),'续租谈成了，没涨。你把合同拍照存档，顺手也拍了下墙角那块霉斑。'],
  ['beat_486','housing','awkward',[30,59],req([p('housing.status','eq','renting'),p('relationships.childCount','eq',0),p('relationships.partnerStatus','in',['none','divorced','widowed']),p('housing.arrangement','eq','solo')]),'房东来修水管，顺口问你一个人住这么大干嘛。房子四十平。'],
  ['beat_487','housing','friction',[30,59],req(),'楼上开始装修。告示写工期两周，你数到第五周不数了。'],
  ['beat_488','health','ordinary',[35,59],req(),'走路多的那几天，你换了双鞋底更软的鞋。第二天还是穿了旧的那双。'],
  ['beat_489','health','awkward',[35,59],req(),'咖啡从一天三杯降到一杯。算下来省的钱，刚好又订了别的。'],
  ['beat_490','health','friction',[38,59],req([p('health.physical','lt',70)]),'爬到四楼那口气，比去年上得急。你放慢脚步，装作在看手机。'],
  ['beat_491','finance','ordinary',[30,59],req(),'记账软件提醒你本月订阅支出。你取消了两个，忘了自己订过的还有一个。'],
  ['beat_492','finance','awkward',[30,59],req(),'婚礼请柬到了，落款你想了几秒才对上人。随礼的数目倒有公价。'],
  ['beat_493','finance','friction',[35,59],req([p('pressures.money','gte',40)]),'你开始在两个平台比同一件日用品的价格。省下的钱不多，省下的这个习惯很大。'],
  ['beat_494','social','ordinary',[30,59],req(),'常去那家店的老板换了。新老板不知道「老样子」是什么，你重新点了一遍。'],
  ['beat_495','social','awkward',[30,59],req(),'有人问你周末干嘛。你说的和你干的，是两套内容。'],
  ['beat_496','social','friction',[35,59],req([p('pressures.loneliness','gte',30)]),'手机相册提醒「三年前的今天」。照片里那群人，现在各在各的城市。'],
  ['beat_497','origin','major',[20,80],req([p('relationships.parentLost','eq',true)]),'手机通讯录你没删那个号码。套餐停了以后，它拨不通，也一直在。'],
  ['beat_498','origin','ordinary',[20,85],req([p('relationships.parentLost','eq',true)]),'做了一道从小吃到大的菜。原来会接着说下一步的那个人，不在了。'],
  ['beat_499','origin','awkward',[20,80],req([p('relationships.parentLost','eq',true)]),'收拾东西时翻出一张旧挂号单。你盯着科室名称看了半天，没想起那阵家里怎么说的。'],
  ['beat_500','origin','ordinary',[25,90],req([p('relationships.parentLost','eq',true)]),'街上有个背影像了一下。你多走了几步，替自己把这件事圆过去。'],
  ['beat_501','origin','friction',[20,105],req([p('outcomeTags.parentLoss:firstCall','gte',1)],[],[p('outcomeTags.parentLoss:inheritance','gte',1)]),'头七还是百日、谁来定、按谁家的规矩——这些事把没说开的旧账全带了出来。'],
  ['beat_502','origin','major',[40,95],req([p('relationships.parentLost','eq',true)]),'你到了那个年纪：镜子里出现那张脸的时候，你先愣一下，再把水龙头开大一点。'],
  ['beat_503','later','ordinary',[60,105],req(),'那天早餐比昨天晚了一个钟头，煎蛋边缘反而刚好脆。'],
  ['beat_504','later','ordinary',[60,105],req(),'那本数独做到最后两格，你故意留到明天再填。'],
  ['beat_505','later','ordinary',[60,105],req([p('housing.arrangement','eq','solo')]),'那天一个人吃完饭，你没开电视，也不觉得屋里少了什么。'],
].map(([id,track,tone,age,requirements,text]) => ({id,track,tone,age,requirements,text}));

export const FABLE_DECISIONS = [
  {id:'decision_209',track:'education',age:[7,10],requirements:req([p('education.status','eq','enrolled')]),situation:'这次没考好。卷子要家长签字，老师说了订正的期限。放学路上你把书包背带攥出了印子。',prompt:'这张卷子怎么办？',choices:[
    option('回家先自己订正一遍','错题一道道过完，签字的时候，大人的话比你想的少。','后来你还是怕考砸，但不再怕那张要签字的卷子。',[c('add','development.learningHabit',4),c('add','development.selfAdvocacy',2)]),
    option('先找同学对答案','答案抄齐了，签字也拿到了。哪里错的，你其实没看。','对答案的交情留了下来，那几类题一直没弄懂。',[c('add','development.learningHabit',-2),c('add','capabilities.network',1)]),
    option('把卷子压在书包最底下','拖到最后一天，签字是在饭桌上要来的。那顿饭大家都吃得很快。','从那以后，坏消息你总想先捂一捂。',[c('add','development.traumaLoad',3),c('add','development.selfAdvocacy',-2)])]},
  {id:'decision_210',track:'social',age:[8,12],requirements:req(),situation:'周末他们约着出去玩，人是凑齐了才在你面前提起的。有人小声说了句「忘了叫你」。',prompt:'你怎么接这句？',choices:[
    option('下次叫我一声','你把话说了出口。说完脸有点热，但下次真有人来叫你了。','开口要位置这件事，你练得比别人早。',[c('add','development.selfAdvocacy',4),c('add','capabilities.network',1)]),
    option('笑笑说没事','你说没事，也真的一起笑了。回家的路上一个人走得很慢。','把「没事」说得自然，成了你的一项本事。',[c('add','development.traumaLoad',2),c('add','capabilities.resilience',1)]),
    option('自己玩自己的','那个周末你过得不坏。只是他们聊起那天的事时，你插不上话。','一个人待着不难受了——这件事有两面，你后来才知道。',[c('add','development.selfAdvocacy',1),c('add','pressures.loneliness',2)])]},
  {id:'decision_211',track:'health',age:[5,11],requirements:req(),situation:'体育课后那阵疼又来了。上次说的时候，大人正忙，一句「小孩子长身体都这样」就翻篇了。',prompt:'这次还说吗？',choices:[
    option('再说一次，把哪里疼说清楚','你指着具体位置说了第二遍。这次有人放下手里的事看了看你。','身体的事要说两遍才有人听——你记住的是要说第二遍，不是别说。',[c('add','capabilities.healthLiteracy',2),c('add','development.selfAdvocacy',3)]),
    option('忍着，能跑能跳就行','那阵疼后来自己停了。你把它归进「不用说的事」那一栏。','后来再有不舒服，你总会先在心里把它分到「要说」还是「不用说」那一栏。',[c('add','development.traumaLoad',2),c('add','capabilities.resilience',1)]),
    option('跟老师说，不跟家里说','老师让你坐了两节课，还是把电话打给了家里。','你第一次知道，大人们之间有一条你管不了的线。',[c('add','development.selfAdvocacy',2),c('add','pressures.family',1)])]},
  {id:'decision_212',track:'finance',age:[9,12],requirements:req(),situation:'过年剩下的钱在你手里放了一阵，家里说「要不还是我先收着」。收之前，问了你一句。',prompt:'这笔钱怎么放？',choices:[
    option('自己收，记在本子上','你找了个盒子，又找了张纸，把数目写在第一行。','那张纸没留住，记数目的习惯留住了。',[c('add','capabilities.evidence',1),c('add','development.selfAdvocacy',2)]),
    option('给家里收，讲好用途','钱交了出去，用途说定了。你时不时问一句，家里答得也认真。','家里第一次和你「对账」，双方都记得这件事。',[c('add','relationships.originBond',2),c('add','development.routeKnowledge',1)]),
    option('花掉一部分再说','想买的东西到手了。剩下的钱交上去时，谁都没提少了的那块。','先花再说的痛快，你尝得比别人早。',[c('add','desires.freedom.fulfillment',2),c('add','development.learningHabit',-1)])]},
  {id:'decision_213',track:'education',age:[10,12],requirements:req([p('originHousehold.context.educationBudget','gte',42)]),situation:'学校社团报名，你想去的那个不加分，家里觉得另一个「对升学有用」。表格只能填一栏。',prompt:'填哪一个？',choices:[
    option('填自己想去的','你把名字写进了那一栏。家里叹了口气，也签了字。','那间活动室的下午，是你最早一段完全属于自己的时间。',[c('add','capabilities.creativity',2),c('add','development.selfAdvocacy',3),c('add','pressures.family',2)]),
    option('填家里说的那个','有用的那栏填上了。第一次活动你去了，第二次开始数还剩几次。','「有用」这个词，你后来警惕了很多年。',[c('add','development.learningHabit',2),c('add','development.traumaLoad',2)]),
    option('两边商量个条件','说好先上一学期有用的，成绩不掉，下学期换。条件是你先提的。','跟家里谈条件这条路，是这次走通的。',[c('add','capabilities.negotiation',2),c('add','development.selfAdvocacy',2)])]},
  {id:'decision_214',track:'origin',age:[20,105],episode:{id:'parent_loss',lane:'origin',phase:1,role:'start',delayYears:1,deadlineYears:5},requirements:req([p('relationships.parentLost','eq',true)],[],[p('outcomeTags.parentLoss:firstCall','gte',1)]),actors:[{slot:'lostParent',relationAny:['father','mother'],alive:false,personIdPath:'relationships.lastParentLossPersonId',optional:false}],situation:'电话是半夜来的。说完那句话，对面先安静了几秒，然后开始讲时间、地点和要带的证件。你一边听一边找笔，找到了才发现手里已经拿着一支。',prompt:'天亮之前，先做哪件？',choices:[
    option('先回去，路上再说','票是站着的也买了。车窗外天慢慢亮，你把手机攥到发烫，没人打来。','后来你总记得那趟车。想不起日期，记得站了多久。',[c('tag','history','parentLoss:firstCall')]),
    option('先把这几天的事排开','原先答应的事一条条改期。每条都写得很客气，像替别人发的消息。','那几条改期消息你没删。后来翻到，才看出每个字都在抖。',[c('tag','history','parentLoss:firstCall')]),
    option('先打给能一起扛的人','电话拨出去，第一句话没说完整。对面说：你别动，我来安排。','那晚接电话的人，你记了一辈子的好。',[c('tag','history','parentLoss:firstCall')])]},
  {id:'decision_215',track:'origin',age:[20,105],episode:{id:'parent_loss',lane:'origin',phase:2,role:'progress',delayYears:4,deadlineYears:5},requirements:req([p('outcomeTags.parentLoss:firstCall','gte',1),p('outcomeTags.parentLoss:inheritance','gte',1),p('age','gte',21)],[],[p('outcomeTags.parentLoss:belongings','gte',1)]),situation:'屋子总要收拾。柜子最里面那层翻出来的东西，比想象的少，也比想象的具体：几张票据、一个用旧的物件、一沓按年份捆好的纸。',prompt:'这些东西怎么办？',choices:[
    option('一样样看完再定','一下午只清了一层柜子。有张纸你看了很久——上面记的是你小时候的事，字很省。','那张纸后来夹在你自己的证件袋里，搬家也带着。',[c('tag','history','parentLoss:belongings')]),
    option('留几样，其余处理掉','留下的装进一个盒子。装车运走那批，你没看第二眼——看第二眼就留下了。','那个盒子不大。你后来发现，够用了。',[c('tag','history','parentLoss:belongings')]),
    option('先封箱，以后再说','箱子贴了条，写了日期。搬到床底那格的时候，你跟自己说：不是不看，是先放着。','那张条子上的日期越来越旧。箱子一直没催你。',[c('tag','history','parentLoss:belongings')])]},
  {id:'decision_216',track:'origin',age:[30,105],episode:{id:'parent_loss',lane:'origin',phase:3,role:'resolve',delayYears:0,deadlineYears:5},requirements:req([p('outcomeTags.parentLoss:belongings','gte',1)],[],[p('outcomeTags.parentLoss:contact','gte',1)]),situation:'表格填到「紧急联系人」那一栏，你的笔停了一下。原来写惯的那个名字，现在要换一个。',prompt:'这一栏写谁？',choices:[
    option('写那个最可能接电话的人','名字写上了，号码核了一遍。写完你把整张表又从头看了一遍，其实没别的要改。','后来每次填这栏都很快。只有第一次慢。',[c('tag','history','parentLoss:contact')]),
    option('先空着，最后再填','表格其他栏都填完了，这一栏留到交表前一刻。收表的人没注意到什么。','有些空格不是忘了填，是不想那么快填上。',[c('tag','history','parentLoss:contact')]),
    option('写自己的名字加一个备注','你写了自己，备注栏补了句说明。窗口看了一眼，收了。','那以后你开始认真想：以后谁来做你的这一栏。',[c('tag','history','parentLoss:contact')])]},
];

export const DECISION_PRESENTATION = Object.freeze({
  decision_044:{situation:'主管把你叫进工位后面那间小会议室，先问最近怎么样，又给你倒了杯水，然后把门带上。这套顺序，一般都有下文。'},
  decision_050:{situation:'合同到期的日子快到了，交接的事一直没人正式提。上个月新来的两个人被安排坐在你旁边，问的问题一个比一个基础。'},
  decision_057:{situation:'通知让你先去看岗。那地方在城郊，班车一天两趟；宿舍是四人间，热水按时段供。合同和体检表装在同一个信封里。'},
  decision_058:{situation:'你在这个窗口坐了一段时间，谁能办、谁不能办，规矩背得下来。发消息的是家里那边的熟人，平时来往不多，逢年过节没断过。消息是下班前到的。'},
  decision_059:{situation:'名额从上面下来，只有一个。同期几个人里条件最合的是你，领导也这么说。驻点的城市和时长写在文件第二页。'},
  decision_061:{situation:'猎头是从同学那边找到你的，问得很具体：现在带几个人，什么时候能到岗。这事你跟谁都没说，只在午休时算了两遍数。'},
  decision_081:{situation:'不上班的日子过了一段，睡眠好了，人也没那么急了。银行卡余额是每月固定往下走的那种走法，不快，也没有停过。'},
  decision_082:{situation:'白天和夜里的界线越来越模糊。窗帘拉着的时候更容易过；出门要先想好去哪儿、见谁、怎么解释自己在干什么。'},
  decision_083:{situation:'朋友先问你最近怎么样，聊到一半才把事情说出来。预算、周期、能担保的部分都讲了——担保不了的那部分，也讲了。'},
  decision_084:{situation:'简历上那一段空白，自己看着都长。前两次面试寒暄完的第一个问题都落在同一个位置，对方笔尖停在那儿等你说完。'},
  decision_085:{situation:'这样的日子过下来，什么时候踏实、什么时候心慌，你大致有数了。手里的钱还能撑一阵，但撑不到不用再想这件事。'},
  decision_108:{situation:'这个月的固定支出没变，进账少了一截。手机上分期和额度的入口比缴费入口更好找，点两下就能把这个月填平。'},
  decision_109:{situation:'调整后的第一期扣款已经出来了，数字比原来那张表上的大。银行的短信写得很客气，只通报，不商量。'},
  decision_112:{situation:'介绍人是熟面孔，讲的时候只讲赚过的那几个人，名字都说得出来。资料发来是一沓截图，收款账户那一栏写的是个人名字。'},
  decision_113:{situation:'起因是一件小事：一张对账单寄到旧地址，被邻居转了过来。你才发现自己记不全名下到底有几个账户、替谁签过什么。'},
  decision_118:{situation:'医生把话说完的时候没有用「可能」两个字。你听清的只有几个词，剩下的记在了对面递过来的那张纸上。走出门诊楼，外面的天还亮着。'},
  decision_119:{situation:'排班是一张越改越乱的表。谁请假、谁值夜、谁去取药，每一格后面都是一次商量。这个月的商量比上个月难开口。'},
  decision_120:{situation:'训练做了很久，动作已经不用看图。复诊时的那几项数字，这次和上次抄下来的是同一行。康复师说这也算稳定。'},
  decision_121:{situation:'病历本换到第几本已经不记得了。新的方案还有，副作用和费用也都还在。医生把选项摆开，说这次由你决定要不要继续往前推。'},
  decision_161:{situation:'表格发下来要填以后想做什么。同桌写得很快，你把笔转了两圈。家里问过、老师问过，问的都是分数够不够，没人问过你怕丢掉哪一样。'},
  decision_162:{situation:'有阵子你还常提以前想做的那件事，后来提得少了。不是放下了——是每次想起来，都要先算一遍现在的开销和明天几点起。'},
  decision_043:{situation:'学校那边的事已经结束，往后的路要自己排。招聘软件上的对话大多停在「保持联系」。这一封通知是真的写了条件：试用期少两千，转正时间那一栏只写着「视表现而定」。',prompt:'这份要不要接？'},
  decision_047:{situation:'错是昨天下午发现的。谁改的、什么时候改的，版本记录里还查得到。上级把责任说明递过来，说你先签，之后再内部处理。',prompt:'这个字，签不签？'},
  decision_048:{situation:'原来的主管上周走了，位置空着。上面找了你两次。接下它，就要开始给以前一起吃午饭的同事打绩效——同一层的人都知道在问谁。',prompt:'这个位置要不要？'},
  decision_049:{situation:'这几个月厂区和办公室都安静了不少。人事把全员叫进会议室，先讲行业，再讲共渡难关，最后发下来一张「自愿无薪休假」——恢复上班的日期空着。',prompt:'这张纸怎么办？'},
  decision_060:{situation:'一通投诉把窗口推上了热搜。流传的截图里，当天签字的经办人是你。规程走完了，投诉人拿到的答复也确实是那句「已办结」。',prompt:'这事怎么处理？'},
  decision_062:{situation:'跨单位调动走到最后一步，系统里少了七年经历记录。旧单位早就撤并，档案盒不在原来的地方。新岗位要求截止前把这段说清楚。',prompt:'这七年怎么补？'},
  decision_168:{situation:'第一天跟站点的老骑手跑单。对方没讲大道理，只告诉你哪栋楼的电梯藏在消防门后、哪家商场要从卸货口进。这些不在软件的导航里。下一单已经开始倒计时。',prompt:'这一单怎么跑？'},
  decision_169:{situation:'商家还在出餐，保温箱里已经有五单。催得太凶怕拿错，不催，后面的楼栋一起超时。站长的头像亮着。',prompt:'先处理哪一头？'},
  decision_170:{situation:'仓储园区中午不让出门。售卖机里一盒饭的钱接近一小时工资。夜班同事把自带的饭放在休息室那台小冰箱里，位置不多，先到先放。',prompt:'这顿饭怎么吃？'},
  decision_171:{situation:'传送带识别失败，人工件越堆越高。组长在另一头催数字，脚边的黄线已经被纸箱压住。',prompt:'照什么速度做？'},
  decision_172:{situation:'零工市场的大屏同时跳出三单：远处装卸给得多，附近保洁当天结，技能单还没刷新。窗口只给几分钟考虑，屏幕前的人不比单子少。',prompt:'接哪一单？'},
  decision_173:{situation:'超市盘货拖到了凌晨，排班表上第二天仍是七点早班。盘点枪还剩一格电。同事已经开始算回家还有没有夜班车。',prompt:'留还是走？'},
  decision_174:{situation:'奶茶店爆单，外卖屏还在往下滚。店长自己站到封口机前，让每个人轮流去后场喝水。你的班早该下了。',prompt:'这会儿怎么办？'},
  decision_175:{situation:'值班的时候制作、巡视和新人都在你手上。客人排到门外，冰箱温度记录还差一次没填。店长电话占线。',prompt:'先顾哪一样？'},
  decision_176:{situation:'入厂以后才知道分到长白班，隔壁技术组要两班倒，工资另算。宿舍钥匙已经领了，培训表等着签字。',prompt:'就这样定下来？'},
  decision_177:{situation:'顾客在电话里要求立刻退款，声音一直没降下来。你的权限只够小额处理，主管的消息没回，通话计时器还在跳。',prompt:'这通电话怎么收？'},
  decision_178:{situation:'上线前需求第三次变化。产品群里只写了「尽量支持」，没人认领是谁提的。测试环境锁定今晚。',prompt:'今晚交什么？'},
  decision_179:{situation:'报销单缺了一张附件，业务负责人催财务今天付款。供应商的电话已经打到第三次，语气比前两次直接。',prompt:'这单怎么走？'},
  decision_180:{situation:'新系统第一次交到你手里。直属领导录了一段操作视频，又发来一份自己做过的模板，说先照着跑一遍，错了再一起看。这样的交接，你没常碰到。',prompt:'第一遍怎么做？'},
  decision_181:{situation:'项目小群里漏了你。截止前一天，同事才把任务截图转过来，还说「我以为有人告诉你了」。时间不够做完，理由也不好开口讲。',prompt:'这一下怎么接？'},
  decision_182:{situation:'管培轮岗结束，两张去向表摆在面前。核心项目强度大、升得快；边缘团队资源少，直属领导却愿意把目标和支持都写清楚。',prompt:'填哪一张？'},
  decision_183:{situation:'下属按你批准的方案做，结果出了错。上级已经在群里问「谁负责」。绩效表下周要交，你是打分的那个人。',prompt:'群里那句怎么答？'},
  decision_189:{situation:'报名页上热门那门只剩候补，催你尽快确认。真正想学的那一门，开课时间一直没定。年纪写在报名表最上面一行。',prompt:'这次报哪门？'},
  decision_190:{situation:'有人听说你「时间多」。一件临时帮的忙，被问成了每周固定的安排。你不讨厌这件事，只是不想默认答应。',prompt:'这事怎么接？'},
  decision_191:{situation:'那个账号连续几周记得你说过的小事，也总在固定的时间回应。最近开始要求保密，说只差一笔钱就能解决眼下的麻烦。',prompt:'下一步怎么做？'},
  decision_192:{situation:'免费礼物和健康讲座把你带进一个封闭群。里面轮番发「专家」语音、限时名额和退款承诺。你已经付过一笔订金。',prompt:'这笔钱怎么办？'},
  decision_193:{situation:'报到手续已经办完。宿舍的费用、门禁时间和通勤路线摆在一起，没有一个方案能同时合适。钥匙要在开学前领。',prompt:'住哪儿？'},
  decision_194:{situation:'上班和回家的路线已经固定了一阵。押金、通勤时间和家里那扇随时能开的门，各有各的价钱。',prompt:'接下来住哪儿？'},
  decision_195:{situation:'工作或者许可把你带到了新的生活半径。短住可以继续续下去，也可以给日常留一个固定地址。租约到期的日子就在眼前。',prompt:'这一站要不要停下来？'},
  decision_196:{situation:'两个人已经在谈每天怎么过。备用钥匙、通勤和各自能承担的住房开支都摆上了桌，「以后再说」这句不够用了。',prompt:'住法怎么定？'},
  decision_197:{situation:'首付、交易费用、现有的债务和接下来的收入都摊在桌上。银行愿不愿意放款是一件事，往后每个月还得起是另一件。',prompt:'这套房买不买？'},
  decision_198:{situation:'现在的住处开始和洗澡、上下楼、看诊或者照应的时间打架。每一件都能单独凑过去，凑在一起就不行了。',prompt:'改哪一样？'},
});

export const RESULT_TEXT_OVERRIDES = Object.freeze({
  decision_043_choice_1:'入职第二个月，主管说转正要等部门名额。你把那句「视表现而定」翻出来又看了一遍，没发出去。',
  decision_043_choice_2:'HR补了一封邮件，条件写进去了，语气比电话里冷一截。入职那天，带你的人说：你就是那个要邮件的。',
  decision_043_choice_3:'对方回了个「好的」，两个字。招聘软件当晚重新开始推岗位，第一条是同一家。',
  decision_045_choice_1:'金额和解除原因，你逐项让对方写清了才签。交工牌的时候，前台还是笑着说了句明天见。',
  decision_045_choice_2:'新部门确认了岗位和薪资，报到日期也定了。门禁停了一下午——那半天你没敢下楼吃饭。',
  decision_045_choice_3:'你拿着没签字的协议走了，出电梯才发现手心是湿的。第二次坐下来，有争议的几项单独标了出来。',
  decision_046_choice_1:'接了份钱不多但能马上上班的，晚上接着投。第一笔工资到账那天，你先把下一周的花销列了出来，没跟人说这份工作打算做多久。',
  decision_046_choice_2:'报了短期班，把以前的经验往新方向靠。新岗位从低的做起——自我介绍时，你把年限含糊过去了。',
  decision_046_choice_3:'面了几轮都没下文。花销压到最低，零散的活也接。亲戚问起，你说在看几个机会。',
  decision_047_choice_1:'你把版本记录、邮件和会议时间一起交了上去。之后两周，会议邀请少了几个。',
  decision_047_choice_2:'你和同事熬了一晚把交付补上。责任说明那张纸还在抽屉里，你每天开抽屉都看见它。',
  decision_049_choice_2:'你没签离职。合同、停工通知和群里的复工日期都留了下来；日期改了两次，你两次都截了图。',
  decision_187_choice_1:'你把收入和必要开支交了上去，扣款比例写进方案。钱还是进得来，只是每月到账那天，你先看剩下多少，再看该还多少。',
  decision_187_choice_2:'房、车、账户按实际填，名下没有的那栏就空着。填到「其他可处置财产」，你写了一台旧电脑的型号。',
  decision_187_choice_3:'期限过了，账户先冻上。超市结账那次刷了两遍都没过，后面排着人，你说换一张。',
  decision_188_choice_1:'腾房那天来了三个人，一个专门负责拍照。楼下有人问你是不是要搬走，你说换个地方住。',
  decision_188_choice_2:'扣款按实际进账走，必要生活费单列。那张表你背下来了——一个月能自己花的数字，精确到十块。',
  decision_188_choice_3:'住处、照护和最低开销的材料交上去了，等核定。等的这段时间，你没敢换手机号。',
  decision_188_choice_4:'你没签。查封和扣划照旧。下次再谈，起点是现在这个数——比上次大。',
  decision_115_choice_1:'能停的都停了，最急的事交给了能接手的人。第一次治疗完，回去的路走得很慢，谁都没怎么说话。',
  decision_115_choice_2:'治疗拆进了每周的空档，被占用的时段提前圈了出来。恢复慢一些，但没断。问起来，就说家里有点事。',
  decision_115_choice_3:'你两次取消门诊，疼得受不了才临时吃药。进急诊那天是别人叫的车，你还在说没那么严重。',
  decision_117_choice_1:'最后一次复诊。医生说这个不用再治了，以后常规检查就行。出门你在走廊上站了一会儿，没急着走。',
  decision_117_choice_3:'有些东西确实恢复不了了。你开始重新安排日常。把「已经不行的」那一栏写下来的时候，笔停了一会儿。',
  decision_117_choice_4:'你跟医生说眼下真的追不动了。医生没劝，把复诊方式和要留意的信号写给你，纸折了两折。',
  decision_121_choice_1:'你把能接受到哪一步写了下来，签了名。做得动的还是做，做不动的那天再说。',
  decision_121_choice_2:'激进的那些停了。最不能接受的副作用和日常限制，你写在了最前面。',
  decision_132_choice_1:'你记了杯数，也记了第二天手抖没抖。电话打出去的时候，第一句是「我又喝了」。',
  decision_133_choice_3:'你不记了。有安排的日子也照喝。瓶子换成了不响的那种。',
  decision_154_choice_1:'你在殡仪馆的塑料椅上接了第一个电话，对方先问你是否为直系亲属。文件和登记后来一项项核过，口头说法一律没算。',
  decision_154_choice_2:'账户和物件都先不动。你把钥匙、文件和保管位置写在一张纸上，写到「联系人」那栏，只剩自己的名字可填。',
  decision_154_choice_3:'你没动账户，也没卖东西，先去问了程序和期限。回来路上顺手删了通讯录里那个已经不会再响的号码——又撤销了。',
});

export const ECHO_TEXT_OVERRIDES = Object.freeze({
  decision_205_c1:'那半天你睡了一觉。醒来手机上还是那几条未读，一条都没少。',
  decision_205_c2:'该办的还是自己去办了。想找人说说话这件事，又往后放了放。',
  decision_204_c3:'那个周末你没出门，睡到自然醒。群里后来发的照片，你点开看完了。',
  decision_202_c1:'后来你们能在下班后说些真话。至于那个岗位——材料该交还是得交。',
  echo_202:'后来你和小周还偶尔联系。那张招聘截图留在相册里，一直没变成一份工作。',
  decision_198_c4:'有人来搭手了。什么时候洗澡、几点睡，还是你自己说。',
  decision_196_c3:'你们没搬到一起。各自那扇门，后来一直留着。',
  decision_152_c5:'进账少了一截，晚上的时间回来了。别人问你退休了没，你说还没。',
  decision_152_c2:'后来还有人说「你顺手帮个忙」。你笑一笑，没接。',
  echo_146:'药盒空得比上次早。原来的病还在，医生也还在开——这几件得放在一起看。',
  decision_164_c4:'那个证没考下来。简历照投，只是少了一行。',
  decision_163_c4:'有一类岗位从此不用再看了。剩下的还是一个个投。',
  decision_183_c3:'流程后来真的改了。当时是谁批的，会上没人再提，你自己记着。',
  decision_182_c2:'项目小一些。出错那次，领导先问的是哪一步没接上。',
  decision_102_c3:'你确实多知道了一些。孩子换了个你不知道的地方说话。',
  decision_076_c1:'签字前你把数看明白了：账面上那个数字，和这个月能取出来的钱，是两码事。',
  decision_073_c1:'谈第二家的时候，那本手册终于被翻烂了。',
  decision_064_c2:'政策后来又调了一次。账单没断，只是每次都得重新算一遍。',
  decision_063_c4:'那封改条件的邮件还在收件箱里。合同最后没签。',
  decision_063_c3:'远程那份，这次没成。',
  decision_062_c1:'材料补齐了。调令上的日子没改。',
  decision_039_c1:'你投得少了。不合条件的那些，现在第一眼就看得出来。',
  decision_037_c4:'邮箱还是每天刷。期限在往前走，开销也在。',
  decision_037_c3:'申请发出去了。美国那张纸，欧洲这边不认。',
  decision_037_c1:'职位列表越筛越短。「是否需要办理许可」那一栏，每份都得重新答一次。',
  echo_022:'学位审核过了。下一张表最上面一行，问的是接下来做什么。',
  decision_020_c3:'课没耽误。生活里那些没人教的，还是一次次撞出来的。',
  echo_051:'你挑了个方向，简历开始真的往外发。',
});

export const FABLE_CARDS = [
  [0,'会看脸色','屋里的天气，你比谁都先知道。代价是你总在预报别人的阴晴。','negotiation',req([p('originHousehold.context.emotionalSafety','lt',40)]),[c('add','capabilities.negotiation',1),c('add','capabilities.boundary',-1)]],
  [0,'早当家','缴费单你很小就认得。同龄人玩的那些，你少玩了几年。','careSkill',req([p('originHousehold.context.resourceTier','eq','strained')]),[c('add','capabilities.careSkill',1),c('add','capabilities.evidence',1),c('add','capabilities.creativity',-1)]],
  [0,'被夸大的孩子','家里逢人就说你行。你也就不敢不行了。','learning',req([p('originHousehold.context.educationCapital','gte',65)]),[c('add','capabilities.learning',1),c('add','capabilities.resilience',-1)]],
  [18,'面子薄','你办事漂亮，因为丢不起人。求助这个动作，你到现在没练会。','portableSkill',req(),[c('add','capabilities.portableSkill',1),c('add','capabilities.network',-1)]],
  [18,'什么都接','没有你不敢接的活。也没有你敢推的。','portableSkill',req(),[c('add','capabilities.employability',6),c('add','capabilities.boundary',-1)]],
  [35,'靠得住','谁出事都先想到你。你出事的时候，想不出先找谁。','careSkill',req(),[c('add','capabilities.careSkill',1),c('add','capabilities.network',1)],'reliableCarePressure'],
  [35,'精打细算','每一笔钱都花在刀刃上。刀刃以外的日子，过得有点紧。','cashBuffer',req(),[c('add','capabilities.cashBuffer',1),c('add','desires.peace.fulfillment',-4)]],
  [35,'嘴硬','谈判桌上没输过。饭桌上没赢过。','negotiation',req(),[c('add','capabilities.negotiation',1)],'guardedPartnerBond'],
  [55,'老资格','你的经验真的值钱。新东西进不来，也是真的。','portableSkill',req(),[c('add','capabilities.portableSkill',1),c('add','capabilities.learning',-1)]],
  [55,'不肯麻烦人','自己的事自己扛，扛到最后一刻才说。','resilience',req(),[c('add','capabilities.resilience',1),c('add','capabilities.healthLiteracy',-1)],'delayHelpSeeking'],
].map(([drawAge,displayName,text,mechanic,requirements,effects,ongoingModifier])=>({drawAge,displayName,text,mechanic,requirements,effects,...(ongoingModifier?{ongoingModifiers:[ongoingModifier]}:{})}));

export const FABLE_ENDING_PROFILES = [
  ['caregiver','这一生你常常先想到别人的药、别人的饭点。被照顾的人不一定都记得，你的日历记得。','少见',['careGiver'],['先照顾别人的人','替人记复诊的那些年'],'差一点，「照顾别人」就成了你一生的名字。'],
  ['overseasLife','换了语言、换了水土，日子重新学了一遍。乡音留在电话里，生活落在了这里。','罕见',['overseasSettled'],['时差两头的人生','把口音留给电话'],'差一点，你就在那边真正落了地。'],
  ['platformYears','系统派单、系统计时、系统评分。跑了这么多年，路你比地图熟。','少见',['platformDecade'],['系统里的这些年','比导航熟一条近路'],'再跑几年，系统就把你算成老师傅了。'],
  ['lateStudy','别人毕业很多年后，你又坐回了教室。这一次没人替你交学费，也没人替你想读的理由。','罕见',['lateStudy'],['重新当学生的人','三十岁后的课表'],'那间教室，你差一点就回去了。'],
  ['deliberateSolo','不要孩子这件事，你是想清楚才定的。后来也有人问，你答得一年比一年短。','少见',['deliberateSolo'],['想清楚了的人','这一支到你为止'],'差一点，你就把这个决定守到了最后。'],
  ['debtRebuilt','最难的那几年，账单比日历厚。你一笔一笔还完了——没人发奖状，但你自己知道。','罕见',['debtCleared'],['还完最后一笔','干净的征信'],'最后几笔差一点就清了。'],
  ['managedYears','病没有走，你也没有把日子全让给它。治疗和日常互相迁就，谁也没占完。','少见',['chronicCompanion'],['带病把日子过下去','和它商量着过'],'差一点，你就找到和它继续相处的办法。'],
  ['creationFulfilled','你给不挣钱的事留过位置。它没让你红，却确实留下了东西。','罕见',['creationFulfilled'],['手上留过活的人','没红过，也做过'],'那件只为喜欢的事，差一点就真正留下来了。'],
  ['activeSolitudeLife','一个人过，是你挑的。冷清和自由是同一件东西的两面，你两面都收下了。','少见',['activeSolitude','lifeEnded'],['主动独处的人','一个人，过得起'],'差一点，独处就成了你选定的生活，而不是剩下的。'],
  ['closeFriendLife','这一生有人跟你说真话，也听你说完。多少事就是这样撑过去的。','少见',['closeFriend','lifeEnded'],['有人接你电话','说真话的交情'],'差一点，就有一个人一直接你的电话。'],
  ['centenarian','一百岁。见过的时代比认识的人还多，你还记得其中大部分。','极罕',['centenarian'],['活过一百岁','四位数的年份换了一遍'],'就差那么几年，你能看到一百岁的天。'],
  ['stayedHome','你没走。别人的远方轮流时髦，你把一座城过成了熟人。','少见',['stayedRooted'],['没搬过家的人','一座城过完一生'],'差一点，你就把一座城住成了亲人。'],
].map(([id,summary,rarity,signals,titles,nearMissHint])=>({id,summary,rarity,signals,titles,nearMissHint}));

export const ATTITUDES_BY_BEAT = Object.freeze({
  beat_009:[['swallow','也回了收到'],['refuse','没回']], beat_010:[['swallow','签了'],['pushBack','问了句真自愿吗']],
  beat_012:[['swallow','又压了一天'],['lean','递给了大人']], beat_013:[['swallow','接了'],['deadpan','就当专业对口']],
  beat_014:[['note','盯着自己那栏'],['deadpan','先笑了一下']], beat_015:[['swallow','硬着头皮递'],['lean','先把话说软']],
  beat_043:[['deadpan','你也没吭声'],['pushBack','把制度甩了链接']], beat_045:[['swallow','写了说明'],['note','把加班也记了']],
  beat_048:[['deadpan','收藏了这条'],['swallow','说了声谢谢']], beat_051:[['note','截了图'],['deadpan','恭喜第一名']],
  beat_053:[['refuse','明早再回',[c('add','desires.freedom.fulfillment',1)]],['swallow','回了「在」']], beat_054:[['swallow','报了名',[c('add','pressures.career',1)]],['refuse','装没看见']],
  beat_058:[['note','查了下末班车'],['deadpan','把通勤算进发展']],
  beat_060:[['deadpan','理解了一下'],['note','记下是第几次']], beat_062:[['swallow','先上着'],['lean','找排班的谈了谈']],
  beat_077:[['deadpan','和复印店混熟了'],['note','把清单抄了下来']], beat_080:[['swallow','说了场面话'],['refuse','这次没发言']],
  beat_084:[['swallow','替系统道了歉'],['pushBack','把问题往上报']], beat_087:[['swallow','先认下来'],['note','把流程出处找齐']],
  beat_093:[['pushBack','当场提了'],['note','先留了证据']], beat_108:[['swallow','又熬了一晚'],['refuse','把时差还给对方']],
  beat_110:[['deadpan','点了个赞'],['note','把公式存了档']], beat_112:[['swallow','还是回了'],['refuse','休完再说']],
  beat_142:[['swallow','给了老价'],['deadpan','指了指通知']], beat_145:[['swallow','又免了一次'],['refuse','这回收了钱']],
  beat_146:[['deadpan','应了声哎'],['pushBack','报了全名']], beat_150:[['lean','先跟员工交底'],['swallow','自己垫了']],
  beat_171:[['deadpan','谢谢它'],['refuse','卸了又装回来']], beat_172:[['deadpan','让对方试试'],['swallow','笑笑没接']],
  beat_175:[['swallow','发了个表情'],['deadpan','说在搞大事']], beat_177:[['deadpan','顺着夸了'],['swallow','嗯了一声']],
  beat_203:[['note','记住了谁点的菜'],['deadpan','真信了一秒']], beat_206:[['lean','过去搭了把手'],['swallow','先躲书房']],
  beat_208:[['deadpan','问回去了'],['swallow','低头夹菜']], beat_210:[['refuse','取消了'],['note','截图留了念']],
  beat_237:[['lean','认真讲了一遍'],['deadpan','说树上长的']], beat_240:[['swallow','放在门口'],['deadpan','敲门收快递费']],
  beat_242:[['swallow','收到就好'],['lean','多问了一句']], beat_246:[['pushBack','先听孩子说'],['swallow','还是续了费']],
  beat_247:[['refuse','退了出来'],['pushBack','谈了条件']], beat_268:[['pushBack','坚持写了'],['swallow','这次算了']],
  beat_271:[['deadpan','升得悄无声息'],['note','把明细拉了出来']], beat_272:[['deadpan','让对方先上'],['swallow','听完没接话']],
  beat_273:[['refuse','挂了'],['note','举报了号码']], beat_279:[['lean','跟家里说了实话',[c('add','pressures.family',-1)]],['swallow','说是推销的']],
  beat_299:[['note','把症状写成清单'],['deadpan','迟到的自觉']], beat_301:[['note','设了复查提醒'],['swallow','先合上了']],
  beat_302:[['lean','跟人提了一嘴'],['swallow','靠咖啡顶住']], beat_304:[['swallow','没跟人说'],['lean','让人陪了几天',[c('add','pressures.body',-1)]]],
  beat_336:[['deadpan','最后一把'],['note','看了眼时间']], beat_341:[['deadpan','物流闭环'],['note','把订单数了数']],
  beat_363:[['refuse','只接了一件'],['swallow','都应了']], beat_366:[['lean','接了，聊了很久'],['refuse','没接']],
  beat_368:[['swallow','收到也行'],['deadpan','比已读强']], beat_369:[['note','先算了一遍'],['swallow','直接续了']],
  beat_372:[['refuse','说完挺轻松',[c('add','desires.freedom.fulfillment',2)]],['note','记下这一天']], beat_380:[['refuse','静音到晚上'],['deadpan','全部点了赞']],
  beat_460:[['deadpan','回了个嘘'],['swallow','戴上了耳机']], beat_464:[['refuse','写了「不想」',[c('add','desires.freedom.fulfillment',1)]],['swallow','编了个理由']],
  beat_473:[['deadpan','你说已经在了'],['note','下次早半小时叫']],
});

export const attitudesFor = (id) => (ATTITUDES_BY_BEAT[id] || []).map(([key,text,effects=[]])=>({key,text,effects}));
