export const UI_COPY={
  homeTagline:'你出生在什么家，很多事一开始就不一样。后面的路，得自己一段一段走。',
  birthTitle:'你出生了',
  birthHouseholdNote:'家里有房有债，但都不是刚出生的你的。',
  birthNext:'分配起点',
  attributesTitle:'你天生更靠什么',
  attributesLead:'起点不能选，但这二十点花在哪儿，由你。',
  attributesConfirm:'就这样出生',
  cardPrompts:{
    0:'你带着什么开始这一生？',
    18:'成年时，你最先学会了什么？',
    35:'这些年，什么成了你的底气？',
    55:'走到这里，你留下了哪样本事？'
  },
  streamEmpty:'点一下，第一年开始。',
  consequenceLabel:'以前的事又回来了',
  activityField:'现在在干嘛',
  netWorthField:'手里净资产',
  habitField:'成瘾与戒断',
  activeArcsTitle:'还有几件事没完',
  noActiveArcs:'眼下没有拖着没完的事',
  coreConflictLabel:'这一生最难两全的事',
  advancePrompt:'点一下，日子继续',
  involvedLabel:'这件事还牵着',
  codexTitle:'人间见闻',
  codexLocked:'还没遇到',
  codexUnlocked:'你已经亲身碰到过这件事。',
  restart:'再活一遍',
  endingTurnsTitle:'这一生真正拐弯的三次',
  endingLedgerTitle:'最后留下的账',
  axisLabels:{
    自主:'自己做主',
    关系:'身边的人',
    健康:'身体',
    安全:'手里的余地',
    欲望兑现:'最想要的东西',
    社会影响:'留下的动静'
  }
};
