export const EMPLOYMENT_COPY={
  label:'受雇工作',
  beatMix:{ordinary:10,awkward:8,friction:8,pressure:4,major:2},
  beats:[
    {tone:'ordinary',text:'工牌发下来时，照片还是入职那天拍的。'},
    {tone:'ordinary',text:'楼下早餐店记住了你几点打卡。'},
    {tone:'ordinary',text:'同事离职后，你们约过两次吃饭。'},
    {tone:'ordinary',text:'今年没换工作，工资也没怎么动。'},
    {tone:'ordinary',text:'新工位离空调近，下午总得穿外套。'},
    {tone:'ordinary',text:'排班表改了三次，你的周末落在周二。'},
    {tone:'ordinary',text:'团建照片发进群，第二天没人再点开。'},
    {tone:'ordinary',text:'工资到账那天，房租也刚好扣走。'},
    {tone:'ordinary',text:'主管换了头像，催进度的语气没变。'},
    {tone:'ordinary',text:'你终于记住了会议室投影仪怎么开。'},
    {tone:'awkward',text:'新同事问年假，群里安静了半分钟。'},
    {tone:'awkward',text:'公司送了保温杯，杯身印着奋斗者。'},
    {tone:'awkward',text:'迟到一分钟要说明，加班两小时不用。'},
    {tone:'awkward',text:'大家轮流说建议，最后按原方案执行。'},
    {tone:'awkward',text:'你在厕所隔间听见领导谈优化名单。'},
    {tone:'awkward',text:'调休申请通过时，原定周末已经过去。'},
    {tone:'awkward',text:'绩效面谈先聊成长，最后只涨了称呼。'},
    {tone:'awkward',text:'离职同事退群后，表情包还留在收藏。'},
    {tone:'friction',text:'HR说工资保密，部门群却公开排名。'},
    {tone:'friction',text:'合同写双休，排班表把周六算机动。'},
    {tone:'friction',text:'客户晚上十一点发来一句“在吗”。'},
    {tone:'friction',text:'主管让你“自愿报名”周末支援。'},
    {tone:'friction',text:'报销单退回三次，每次理由都不一样。'},
    {tone:'friction',text:'组织优化后，两个人接了五个人的活。'},
    {tone:'friction',text:'招聘时说扁平，出错时层级全回来了。'},
    {tone:'friction',text:'公司搬远了，通勤每天多出九十分钟。'},
    {tone:'pressure',text:'项目延期，负责人名单上只有你的名字。'},
    {tone:'pressure',text:'工资晚发半个月，财务让大家再理解一下。'},
    {tone:'pressure',text:'裁员邮件发出前，门禁先刷不开了。'},
    {tone:'pressure',text:'体检报告建议休息，排班表已经排到下月。'},
    {tone:'major',text:'部门撤掉那天，你的工牌还能刷到下午。'},
    {tone:'major',text:'干了二十年，退休手续还差一段社保记录。'}
  ],
  decisions:[
    {
      prompt:'HR发来录用通知：试用期少两千，转正时间只写了“视表现而定”。',
      echoText:'那份录用通知后来又被翻了出来。',
      choices:[
        {text:'先进去再说',resultText:'入职第二个月，主管说转正要等部门名额。',consequenceText:'半年后，名额还没下来，试用期工资倒是一直按时发。'},
        {text:'让HR写进邮件',resultText:'HR补了一封邮件，语气明显没电话里热情。',consequenceText:'谈补偿时，你翻出那封邮件，多拿回了两个月工资。'},
        {text:'不去了，继续投',resultText:'对方很快回了“好的”，招聘软件重新开始推岗位。',consequenceText:'下一份工资高了些，你也多空窗了四个月。'}
      ]
    },
    {
      prompt:'主管说可以涨薪，但从下个月起，周末也要随时回消息。',
      echoText:'那次涨薪谈话后来有了下文。',
      choices:[
        {text:'接下涨薪和职责',resultText:'新工资写进了系统，周六上午也多了一个固定会议。',consequenceText:'一年后，工资确实高了，家里也不再默认周末能找到你。'},
        {text:'先把加班写清楚',resultText:'主管删掉了“随时响应”，改成每月最多两个周末值班。',consequenceText:'后来部门换了负责人，你拿着旧邮件把排班争议挡了回去。'},
        {text:'不要这次涨薪',resultText:'你保留了原岗位，主管只回了一句“尊重个人选择”。',consequenceText:'下一轮晋升名单没有你，周末倒一直还是自己的。'}
      ]
    },
    {
      prompt:'公司通知部门要“优化”，给你内部转岗、拿补偿或自己离开三个选项。',
      echoText:'那轮“优化”没有停在通知当天。',
      choices:[
        {text:'转去另一个部门',resultText:'新部门先收走工牌权限，又重新给你开了一套。',consequenceText:'半年后原部门解散，你在新群里看见了那张名单。'},
        {text:'核对补偿再走',resultText:'你把工资流水和年假截图发给人事，补偿表改了两处。',consequenceText:'空窗第三个月，那笔补偿正好撑到新工作的入职日。'},
        {text:'主动辞职转行',resultText:'离职证明开得很快，转行课程的报名页还停在付款前。',consequenceText:'新行业没那么快接住你，社保中间断了五个月。'}
      ]
    },
    {
      prompt:'猎头给的工资高一截，但合同只签一年，到期是否续约没人肯写。',
      echoText:'那份一年期合同走到了续约前。',
      choices:[
        {text:'接下一年合同',resultText:'你在原公司办完离职，周一拿到了新门禁卡。',consequenceText:'合同到期前两个月，续约名额果然开始重新审批。'},
        {text:'拿报价回去谈',resultText:'现公司补了一部分工资，也把竞业条款翻了出来。',consequenceText:'第二年调薪时，主管又提起你当年差点走。'},
        {text:'留在原岗位',resultText:'猎头说以后保持联系，聊天框很快沉了下去。',consequenceText:'原公司后来裁掉了新业务，你的岗位暂时没动。'}
      ]
    },
    {
      prompt:'项目出了错，上级让你先在责任说明上签字，说之后再内部处理。',
      echoText:'那份责任说明进了后来的一次审计。',
      choices:[
        {text:'保存记录如实说明',resultText:'你把版本记录、邮件和会议时间一起交了上去。',consequenceText:'客户追责时，调查组按时间线找到了真正改过文件的人。'},
        {text:'先补救再说明',resultText:'你和同事熬了一晚把交付补上，责任说明暂时没发。',consequenceText:'项目保住了，复盘会上却只写了“团队主动整改”。'},
        {text:'替上级签字',resultText:'上级拍了拍你，说年底绩效不会亏待你。',consequenceText:'年底评级没变，那份签字文件倒一直留在审计系统里。'}
      ]
    },
    {
      prompt:'主管岗位空出来了。接下它，你要开始给以前一起吃午饭的同事打绩效。',
      echoText:'那次晋升后来落到了具体的人身上。',
      choices:[
        {text:'接下管理岗',resultText:'人事给你换了职级，原来的同事开始叫你领导。',consequenceText:'第一次末位沟通时，坐你对面的是带你入职的人。'},
        {text:'只走专业线',resultText:'你保留了项目和涨薪，不再参加排班审批会。',consequenceText:'几年后公司另设专家岗，你的技术记录终于能直接算业绩。'},
        {text:'这次不升了',resultText:'名单发出前，你把名字撤了回来。',consequenceText:'新主管上任后，你的工作没少，只是不再由你决定优先级。'}
      ]
    },
    {
      prompt:'订单少了，公司让大家签“自愿无薪休假”，恢复上班的日期空着。',
      echoText:'那张无薪休假单后来又出现了一次。',
      choices:[
        {text:'休假去学新技能',resultText:'你没签离职，在家开始上晚课，社保仍由公司缴。',consequenceText:'复工通知来得很晚，课程证书先一步发到了邮箱。'},
        {text:'要求按合同处理',resultText:'人事把“自愿”两个字删了，重新发来待岗工资方案。',consequenceText:'公司后来补发工资时，你的名字在第一批名单里。'},
        {text:'先离职再找',resultText:'离职手续当天办完，招聘软件却比上个月安静得多。',consequenceText:'三个月后你才入职，谈工资时已经没了在职筹码。'}
      ]
    },
    {
      prompt:'退休手续快办完时，公司想让你再带一年新人，工资另算。',
      echoText:'那次退休前的约定到了期限。',
      choices:[
        {text:'返聘一年写清期限',resultText:'返聘合同写到具体日期，带的新人也列进了附件。',consequenceText:'一年到期，公司又来问时，新人已经能自己值班了。'},
        {text:'只做短期顾问',resultText:'你每周去两天，不再参加部门考勤和临时会议。',consequenceText:'项目交接结束后，你的门禁权限按约定当天关闭。'},
        {text:'按计划退休',resultText:'你把工牌交回前台，工作群在下午安静地退了。',consequenceText:'下个月发薪日，手机没有到账短信，养老金晚两天来了。'}
      ]
    }
  ]
};
